import { Utils } from '../utils/utils.js';
import { publishComponentApi } from './componentRuntime.js';
import { Carousel } from '../components/carousel.js';
import { Collapse } from '../components/collapse.js';
import { Loading } from '../components/loading.js';
import { InputNumber } from '../components/input-number.js';
import { InputOTP } from '../components/input-otp.js';
import { Progress } from '../components/progress.js';
import { Rate, RATE_SIZES } from '../components/rate.js';
import { Result } from '../components/result.js';
import { Steps, STEPS_SIZES } from '../components/steps.js';
import { Sort } from '../components/sort.js';
import { Slider, SLIDER_SIZES } from '../components/slider.js';
import { TagInput } from '../components/tag-input.js';
import { Popover } from '../components/popover.js';
import { Popconfirm } from '../components/popconfirm.js';
import { Tooltip } from '../components/tooltip.js';
import { Dropdown } from '../components/dropdown.js';
import { Modal, PLACEMENTS as MODAL_PLACEMENTS } from '../components/modal.js';
import { Drawer, PLACEMENTS as DRAWER_PLACEMENTS, ANIMATIONS as DRAWER_ANIMATIONS } from '../components/drawer.js';
import { Autocomplete } from '../components/autocomplete.js';
import { Select } from '../components/select.js';
import { Cascader } from '../components/cascader.js';
import { TreeSelect } from '../components/tree-select.js';
import { WheelPicker } from '../components/wheel-picker.js';
import { TimePicker } from '../components/time-picker.js';
import { ColorPicker } from '../components/color-picker.js';
import { DatePicker } from '../components/date-picker.js';
import { Trigger } from '../components/trigger.js';
import { Scroll } from '../components/scroll.js';
import { Ripple } from '../components/ripple.js';
import { Menu } from '../components/menu.js';
import { Transfer } from '../components/transfer.js';
import { Tabs } from '../components/tabs.js';
import { Image } from '../components/image.js';
import { JSONComponent } from '../components/json.js';
import { Pagination } from '../components/pagination.js';
import { Tags } from '../components/tags.js';
import { Upload } from '../components/upload.js';
import { Table } from '../components/table.js';
import { Message } from '../components/message.js';
import { Notification } from '../components/notification.js';

const createInitializer = Object.freeze({ initializer:Object.freeze({ mode:'create', bind:'container' }) });
const enhanceInitializer = Object.freeze({ initializer:Object.freeze({ mode:'enhance' }) });
const sourceInitializer = Object.freeze({ initializer:Object.freeze({ mode:'create', bind:'source' }) });
const referenceInitializer = Object.freeze({ initializer:Object.freeze({ mode:'create', bind:'reference' }) });
const noInitializer = Object.freeze({ initializer:false });

function classApi(Type, extras = {}) {
    const base = { definition:createInitializer, create:function(){ return Type.create.apply(Type, arguments); } };
    if (Type.profile) base.profile = Type.profile;
    return Object.freeze(Utils.assignOwn(base, extras));
}
const raw = Object.create(null);
raw.Cascader = classApi(Cascader, { definition:enhanceInitializer, enhance:function(){return Cascader.enhance.apply(Cascader,arguments);}, createDefaultDOM:Cascader.createDefaultDOM });
raw.TreeSelect = classApi(TreeSelect, { definition:enhanceInitializer, enhance:function(){return TreeSelect.enhance.apply(TreeSelect,arguments);}, createDefaultDOM:TreeSelect.createDefaultDOM });
raw.Select = classApi(Select, { definition:enhanceInitializer, enhance:function(){return Select.enhance.apply(Select,arguments);}, createDefaultDOM:Select.createDefaultDOM });
raw.Autocomplete = classApi(Autocomplete, { definition:enhanceInitializer, enhance:function(){return Autocomplete.enhance.apply(Autocomplete,arguments);}, createDefaultDOM:Autocomplete.createDefaultDOM });
raw.Carousel = classApi(Carousel);
raw.Collapse = classApi(Collapse);
raw.InputNumber = classApi(InputNumber, { definition:enhanceInitializer, enhance:function(){return InputNumber.enhance.apply(InputNumber,arguments);} });
raw.InputOTP = classApi(InputOTP, { definition:enhanceInitializer, enhance:function(){return InputOTP.enhance.apply(InputOTP,arguments);} });
raw.Loading = classApi(Loading, { definition:noInitializer });
raw.Progress = classApi(Progress);
raw.Slider = classApi(Slider, { definition:sourceInitializer, enhance:function(){return Slider.enhance.apply(Slider,arguments);}, sizes:SLIDER_SIZES.slice() });
raw.Sort = classApi(Sort, { definition:sourceInitializer, enhance:function(){return Sort.enhance.apply(Sort,arguments);} });
raw.Steps = classApi(Steps, { sizes:STEPS_SIZES.slice() });
raw.Rate = classApi(Rate, { definition:sourceInitializer, enhance:function(){return Rate.enhance.apply(Rate,arguments);}, sizes:RATE_SIZES.slice() });
raw.Tooltip = classApi(Tooltip, { definition:referenceInitializer });
raw.TagInput = classApi(TagInput, { definition:enhanceInitializer, enhance:function(){return TagInput.enhance.apply(TagInput,arguments);} });
raw.Popconfirm = classApi(Popconfirm, { definition:referenceInitializer });
raw.Popover = classApi(Popover, { definition:referenceInitializer });
raw.Dropdown = classApi(Dropdown, { definition:referenceInitializer });
raw.Modal = classApi(Modal, { definition:noInitializer, placements:MODAL_PLACEMENTS.slice() });
raw.Drawer = classApi(Drawer, { definition:noInitializer, placements:DRAWER_PLACEMENTS.slice(), animations:DRAWER_ANIMATIONS.slice() });
raw.Result = classApi(Result, { names:Result.names });
raw.WheelPicker = classApi(WheelPicker, { definition:enhanceInitializer, enhance:function(){return WheelPicker.enhance.apply(WheelPicker,arguments);} });
raw.TimePicker = classApi(TimePicker, { definition:enhanceInitializer, enhance:function(){return TimePicker.enhance.apply(TimePicker,arguments);}, formatTime:TimePicker.formatTime, parseTime:TimePicker.parseTime });
raw.ColorPicker = classApi(ColorPicker, { definition:enhanceInitializer, enhance:function(){return ColorPicker.enhance.apply(ColorPicker,arguments);}, gradientCSS:ColorPicker.gradientCSS });
raw.DatePicker = classApi(DatePicker, { definition:enhanceInitializer, enhance:function(){return DatePicker.enhance.apply(DatePicker,arguments);}, formatDate:DatePicker.formatDate, parseDate:DatePicker.parseDate });

raw.Pagination = classApi(Pagination, { createDefaultDOM:Pagination.createDefaultDOM });
raw.Menu = classApi(Menu, { createDefaultDOM:Menu.createDefaultDOM });
raw.Scroll = classApi(Scroll, { attachViewport:Scroll.attachViewport, createDefaultDOM:Scroll.createDefaultDOM });
raw.Transfer = classApi(Transfer, { definition:sourceInitializer, enhance:function(){return Transfer.enhance.apply(Transfer,arguments);}, createDefaultDOM:Transfer.createDefaultDOM });
raw.Tabs = classApi(Tabs);
raw.Image = classApi(Image, { createPreview:Image.createPreview });
raw.JSON = classApi(JSONComponent);
raw.Tags = classApi(Tags);
raw.Upload = classApi(Upload, { definition:sourceInitializer, enhance:function(){return Upload.enhance.apply(Upload,arguments);}, LIST_IGNORE:Upload.LIST_IGNORE });
raw.Table = classApi(Table, { sizes:Table.sizes.slice() });
Utils.assignOwn(raw, { Trigger, Ripple, Message, Notification });

export const Components = Object.freeze(Object.fromEntries(Object.entries(raw).map(([name, api]) => [name, publishComponentApi(name, api)])));
export const componentTypes = Object.freeze({ Autocomplete, Cascader, Carousel, Collapse, ColorPicker, DatePicker, Drawer, Dropdown, Image, InputNumber, InputOTP, JSON:JSONComponent, Loading, Menu, Modal, Pagination, Popconfirm, Popover, Progress, Rate, Result, Scroll, Select, Slider, Sort, Steps, Table, TagInput, Tags, Tabs, TimePicker, Tooltip, Transfer, TreeSelect, Upload, WheelPicker });
export default Components;
