import re
S='/tmp/claude-0/-home-claude/33a9dde6-00ca-5a12-b42c-ad88ecb4bf0a/scratchpad'
p=S+'/work/src/qx-theme-system.js'; s=open(p).read(); par=open(S+'/parity.js').read().strip()
block='/* PARITY:BEGIN */\n'+par+'\n/* PARITY:END */\n'
if '/* PARITY:BEGIN */' in s: s=re.sub(r'/\* PARITY:BEGIN \*/[\s\S]*?/\* PARITY:END \*/\n', lambda m: block, s)
else: s=re.sub(r'/\* Generated by tools/genparity\.py[\s\S]*?\n\}\);\n', lambda m: block, s, count=1)
if 'PARITY_MODE_KEYS' not in s:
    s=s.replace("const MODE_INPUTS=new Set([","const PARITY_MODE_KEYS=Object.keys(PARITY_MODE.nova.light);\nconst MODE_INPUTS=new Set([...PARITY_MODE_KEYS,",1)
    s=s.replace(" for(const [k,v]of Object.entries(P))put(k,typeof v==='number'?String(v):v);",
     " for(const [k,v]of Object.entries(P))put(k,typeof v==='number'?String(v):v);\n for(const mode of ['light','dark'])for(const [k,v]of Object.entries(PARITY_MODE[c.style][mode]))raw[mode][PREFIX+k]=v;",1)
open(p,'w').write(s); print('ok', s.count('PARITY_MODE'))
