import { PopupComponent } from './popup.js';
import { Trigger } from './trigger.js';
import { componentHooks } from '../core/componentHooks.js';
import { ComponentContracts } from '../core/componentContracts.js';
import { OpenStateBridge } from '../core/openStateBridge.js';
import { TriggerInteraction } from '../core/triggerInteraction.js';
import { LayerManager } from '../core/layerManager.js';
import { Config } from '../core/config.js';
import { DOM } from '../core/dom.js';
import { IdManager } from '../utils/id.js';
import { Utils } from '../utils/utils.js';

const SIZES=Object.freeze(['xs','sm','md','lg','xl']);
const TRIGGERS=Object.freeze(['click','hover','focus','contextMenu','manual']);
const FOLLOW_CURSOR=Object.freeze(['horizontal','vertical','initial']);
const state=new WeakMap();
const own=Utils.own;
function resolveElement(value,documentRef,label){return DOM.requireElement(value,documentRef,'Tooltip '+label);}
function normalizeSize(value){return Utils.normalizeEnum(value==null||value===''?'md':value,SIZES,undefined,'Tooltip size');}
function normalizeTriggers(value){const source=Array.isArray(value)?value.slice():String(value==null?'hover focus':value).split(/\s+/),result=[];source.forEach(item=>{const name=String(item||'').trim();if(!name)return;if(!TRIGGERS.includes(name))throw new TypeError('[QXFRAME9A7C2] Tooltip trigger must use click, hover, focus, contextMenu, or manual.');if(!result.includes(name))result.push(name);});if(!result.length)result.push('hover','focus');if(result.includes('manual')&&result.length>1)throw new TypeError('[QXFRAME9A7C2] Tooltip manual trigger cannot be combined with event triggers.');return result;}
function normalizeFollowCursor(value){if(value===true)return true;if(value===false||value===undefined||value===null)return false;const mode=String(value);if(!FOLLOW_CURSOR.includes(mode))throw new TypeError('[QXFRAME9A7C2] Tooltip followCursor must be true, false, horizontal, vertical, or initial.');return mode;}
function resolvedDelay(value,configKey,element){const resolved=Config.resolve(configKey,value,element||null),number=Number(resolved);return Number.isFinite(number)&&number>0?number:0;}
function renderContent(target,value,context){while(target.firstChild)target.removeChild(target.firstChild);const output=Utils.isFunction(value)?value(context):value;if(output===undefined||output===null)return;if(output&&typeof output==='object'&&typeof output.nodeType==='number')target.appendChild(output);else target.textContent=String(output);}
function createPanel(doc){const panel=doc.createElement('div'),container=doc.createElement('div'),content=doc.createElement('div'),arrow=doc.createElement('div');panel.className='qxframe9a7c2-tooltip-root';panel.id=IdManager.next('tooltip');panel.hidden=true;container.className='qxframe9a7c2-tooltip-container qxframe9a7c2-popup-surface';content.className='qxframe9a7c2-tooltip-content';arrow.className='qxframe9a7c2-tooltip-arrow';container.appendChild(content);panel.appendChild(container);return{panel,container,content,arrow,visualTrigger:null,activeMember:null,internalClose:false};}
function applyPanelView(record,opts,context){SIZES.forEach(size=>record.panel.classList.remove('is-'+size));record.panel.classList.add('is-'+opts.size);record.panel.classList.toggle('has-arrow',opts.showArrow===true);if(opts.showArrow===true){if(record.arrow.parentNode!==record.container)record.container.appendChild(record.arrow);}else if(record.arrow.parentNode)record.arrow.parentNode.removeChild(record.arrow);record.panel.setAttribute('data-placement',String(opts.placement||'top'));renderContent(record.content,opts.content,context);}
function requireState(instance){const r=state.get(instance);if(!r)throw new TypeError('[QXFRAME9A7C2] Invalid Tooltip instance.');return r;}

export class Tooltip extends PopupComponent {
    static contract=ComponentContracts.get('Tooltip');
    static options=Object.freeze({trigger:'hover focus',placement:'top',showArrow:true,arrowPadding:8,size:'md',fresh:false,open:false,disabled:false,closeOnEscape:true,autoUpdate:true,group:null,unique:false,followCursor:false,inlinePositioning:false,interactiveBorder:0,interactiveDebounce:0});
    static optionNormalizers=Object.freeze({size:normalizeSize,followCursor:normalizeFollowCursor});

    [componentHooks.beforeOptionsUpdate](patch,previous){const r=requireState(this);if(own(patch,'reference')&&resolveElement(patch.reference,r.doc,'reference')!==r.reference)throw new Error('[QXFRAME9A7C2] Tooltip reference is immutable; destroy and recreate to change it.');if(own(patch,'portalContainer')&&resolveElement(patch.portalContainer,r.doc,'portalContainer')!==r.portalContainer)throw new Error('[QXFRAME9A7C2] Tooltip portalContainer is immutable; destroy and recreate to change it.');if(own(patch,'group')||own(patch,'unique')||own(patch,'parentLayerId')){const nextGroup=own(patch,'group')?patch.group:previous.group,nextUnique=own(patch,'unique')?patch.unique:previous.unique,normalized=nextGroup===undefined||nextGroup===null||nextGroup===''?(nextUnique===true?'__default__':null):String(nextGroup);if(normalized!==r.group||(own(patch,'parentLayerId')&&patch.parentLayerId!==previous.parentLayerId))throw new Error('[QXFRAME9A7C2] Tooltip group/unique/parentLayerId are immutable; destroy and recreate to change singleton identity.');}}

    [componentHooks.render](opts){normalizeTriggers(opts.trigger);const doc=opts.document||(opts.reference&&opts.reference.ownerDocument)||globalThis.document,sharedLayerManager=LayerManager.getShared(doc),reference=resolveElement(opts.reference,doc,'reference'),portalContainer=opts.portalContainer?resolveElement(opts.portalContainer,doc,'portalContainer'):doc.body;if(!portalContainer)throw new TypeError('[QXFRAME9A7C2] Tooltip requires document.body or portalContainer.');
        const group=opts.group===undefined||opts.group===null||opts.group===''?(opts.unique===true?'__default__':null):String(opts.group),resolvedParentLayerId=opts.parentLayerId||(sharedLayerManager.findParentId?sharedLayerManager.findParentId(reference):null)||null,grouped=!!group,ownRecord=grouped?null:createPanel(doc),ownerRoot=doc.createElement('span');let groupLease=null,record=ownRecord,triggerSession=null,interaction=null,pointerMoveCleanup=null,opened=false,contentDirty=false,cursor={x:null,y:null,initialX:null,initialY:null,initialSet:false};
        if(grouped){groupLease=sharedLayerManager.acquireSingleton({type:'Tooltip',group,parentId:resolvedParentLayerId,create:()=>createPanel(doc),onLastRelease:shared=>{if(shared.visualTrigger)shared.visualTrigger.destroy('tooltip-singleton-release');shared.visualTrigger=null;shared.activeMember=null;DOM.removeNode(shared.panel);}});record=groupLease.value;record.panel.setAttribute('data-qxframe9a7c2-tooltip-singleton',group);}
        const runtime={doc,reference,portalContainer,group,resolvedParentLayerId,grouped,record,ownerRoot,get triggerSession(){return triggerSession;},get interaction(){return interaction;},set interaction(v){interaction=v;},get pointerMoveCleanup(){return pointerMoveCleanup;},set pointerMoveCleanup(v){pointerMoveCleanup=v;},get opened(){return opened;},set opened(v){opened=v;},get contentDirty(){return contentDirty;},set contentDirty(v){contentDirty=v;},cursor,groupLease,member:null,syncOptions:null,setContent:null};state.set(this,runtime);
        const sourceOf=event=>DOM.activationSource(event||null),detail=(reason,originalEvent,source)=>({source:source||sourceOf(originalEvent),reason:reason||'api',originalEvent:originalEvent||null,tooltip:this,state:{open:opened}}),emitOpen=(value,info)=>OpenStateBridge.dispatch(value,info,{emitter:{emit:(name,payload)=>this.emit(name,payload)},emitPhase:true,decorate:()=>({opened:value,tooltip:this}),onOpen:payload=>{if(Utils.isFunction(this.options.onOpen))this.options.onOpen(payload);},onClose:payload=>{if(Utils.isFunction(this.options.onClose))this.options.onClose(payload);},onChange:(next,payload)=>{if(Utils.isFunction(this.options.onOpenChange))this.options.onOpenChange(next,payload);},isCurrent:()=>!this.destroyed&&opened===value}),beforeOpen=info=>!this.destroyed&&this.options.disabled!==true&&(!Utils.isFunction(this.options.beforeOpen)||this.options.beforeOpen(info,this)!==false),beforeClose=info=>!Utils.isFunction(this.options.beforeClose)||this.options.beforeClose(info,this)!==false;
        const referenceRect=()=>reference.getBoundingClientRect?reference.getBoundingClientRect():{left:0,top:0,right:0,bottom:0,width:0,height:0};const virtualReference={contextElement:reference,getBoundingClientRect:()=>{const rect=referenceRect(),centerX=Number(rect.left||0)+Number(rect.width||((rect.right||0)-(rect.left||0)))/2,centerY=Number(rect.top||0)+Number(rect.height||((rect.bottom||0)-(rect.top||0)))/2,mode=this.options.followCursor;let x=cursor.x==null?centerX:cursor.x,y=cursor.y==null?centerY:cursor.y;if(mode==='initial'){x=cursor.initialSet?cursor.initialX:x;y=cursor.initialSet?cursor.initialY:y;}if(mode==='horizontal')y=centerY;if(mode==='vertical')x=centerX;return{x,y,left:x,right:x,top:y,bottom:y,width:0,height:0};}};const positionReference=()=>this.options.followCursor?virtualReference:null;
        const updateCursor=event=>{if(!this.options.followCursor||!event)return;const x=Number(event.clientX),y=Number(event.clientY);if(!Number.isFinite(x)||!Number.isFinite(y))return;cursor.x=x;cursor.y=y;if(!cursor.initialSet){cursor.initialX=x;cursor.initialY=y;cursor.initialSet=true;}if(opened){const visual=grouped?record.visualTrigger:triggerSession;if(visual)visual.reposition('follow-cursor');}},resetCursor=()=>{cursor.initialSet=false;cursor.initialX=cursor.initialY=null;},rebuildPointerTracking=()=>{if(pointerMoveCleanup){pointerMoveCleanup();pointerMoveCleanup=null;}if(!this.options.followCursor||this.destroyed)return;pointerMoveCleanup=DOM.listen(reference,'pointermove',updateCursor);},syncOwnView=force=>{const o=this.options;if(!force&&o.fresh!==true&&!contentDirty)return;applyPanelView(record,o,this);contentDirty=false;};
        const commonTriggerOptions=()=>{const o=this.options;return{placement:o.placement,arrow:o.showArrow===true,arrowElement:record.arrow,arrowPadding:o.arrowPadding,offset:o.offset,strategy:o.strategy||'absolute',middleware:o.middleware,autoUpdate:o.autoUpdate!==false,closeOnOutsidePress:false,closeOnEscape:o.closeOnEscape!==false,destroyOnClose:o.destroyOnClose!==false,restoreFocus:false,disabled:o.disabled===true,parentLayerId:resolvedParentLayerId,layerKind:'tooltip',componentType:'Tooltip',group,zIndex:o.zIndex,positionReference:positionReference(),useTransformPosition:true,inlinePositioning:o.inlinePositioning===true,inlinePositioningOptions:o.inlinePositioningOptions};};
        const createIndependentTrigger=()=>Trigger.create(Object.assign(commonTriggerOptions(),{reference,floating:record.panel,transitionElement:record.container,document:doc,portalContainer,trigger:this.options.trigger,transition:Trigger.motion.popupPlacement,openDelay:this.options.openDelay,closeDelay:this.options.closeDelay,interactiveBorder:this.options.interactiveBorder,interactiveDebounce:this.options.interactiveDebounce,beforeOpen:info=>beforeOpen(detail(info.reason,info.originalEvent,info.source)),beforeClose:info=>beforeClose(detail(info.reason,info.originalEvent,info.source)),onOpen:info=>{opened=true;if(this.options.fresh===true||contentDirty)syncOwnView(true);record.panel.classList.add('is-open');emitOpen(true,detail(info.reason,info.originalEvent,info.source));},onClose:info=>{opened=false;record.panel.classList.remove('is-open');resetCursor();emitOpen(false,detail(info.reason,info.originalEvent,info.source));}}));
        const ensureGroupVisual=()=>{if(record.visualTrigger)return record.visualTrigger;record.visualTrigger=Trigger.create(Object.assign(commonTriggerOptions(),{reference,floating:record.panel,transitionElement:record.container,allowReferenceUpdate:true,document:doc,portalContainer,trigger:'manual',transition:Trigger.motion.popupPlacement,beforeClose:info=>{if(record.internalClose)return true;const member=record.activeMember;return!member||member.canVisualClose(info.reason,info.originalEvent,info.source);},onClose:info=>{if(record.internalClose)return;const member=record.activeMember;if(member)member.visualClosed(info.reason,info.originalEvent,info.source);record.activeMember=null;}}));return record.visualTrigger;};
        const member=grouped?{api:()=>this,isOpen:()=>opened,canVisualClose:(reason,event,source)=>beforeClose(detail(reason,event,source)),visualClosed:(reason,event,source)=>{if(!opened)return;opened=false;record.panel.classList.remove('is-open');resetCursor();emitOpen(false,detail(reason,event,source));},switchOut:event=>{if(!opened)return;opened=false;resetCursor();emitOpen(false,detail('singleton-switch',event));}}:null;runtime.member=member;
        const syncGroupVisual=()=>{applyPanelView(record,this.options,this);contentDirty=false;const visual=ensureGroupVisual();visual.updateOptions(Object.assign(commonTriggerOptions(),{reference,allowReferenceUpdate:true,transitionElement:record.container,trigger:'manual',disabled:false}));return visual;},groupOpen=(reason,originalEvent)=>{if(this.destroyed||this.options.disabled===true||opened)return false;const info=detail(reason||'api',originalEvent||null);if(!beforeOpen(info))return false;const previous=record.activeMember;if(previous&&previous!==member)previous.switchOut(originalEvent||null);record.activeMember=member;const visual=syncGroupVisual();opened=true;record.panel.classList.add('is-open');if(!visual.getState().open){if(visual.open(reason||'api',originalEvent||null)!==true){opened=false;record.activeMember=null;return false;}}else visual.reposition('singleton-switch');emitOpen(true,info);return true;},groupClose=(reason,originalEvent)=>{if(this.destroyed||!opened)return false;const info=detail(reason||'api',originalEvent||null);if(!beforeClose(info))return false;opened=false;resetCursor();record.panel.classList.remove('is-open');emitOpen(false,info);if(record.activeMember===member){record.internalClose=true;try{if(record.visualTrigger&&record.visualTrigger.getState().open)record.visualTrigger.close(reason||'api',originalEvent||null);}finally{record.internalClose=false;record.activeMember=null;}}return true;};
        const rebuildGroupInteraction=()=>{if(!grouped)return;if(interaction){interaction.destroy();interaction=null;}const triggers=normalizeTriggers(this.options.trigger);if(this.destroyed||this.options.disabled===true||triggers.includes('manual'))return;interaction=TriggerInteraction.create({reference,floating:record.panel,trigger:triggers,openDelay:()=>resolvedDelay(this.options.openDelay,'triggerOpenDelay',reference),closeDelay:()=>resolvedDelay(this.options.closeDelay,'triggerCloseDelay',reference),interactiveBorder:this.options.interactiveBorder,interactiveDebounce:this.options.interactiveDebounce,containsTarget:target=>reference===target||reference.contains(target)||record.panel===target||record.panel.contains(target),onOpenIntent:(reason,event)=>groupOpen(reason,event),onCloseIntent:(reason,event)=>groupClose(reason,event),onToggleIntent:(reason,event)=>opened?groupClose(reason,event):groupOpen(reason,event)});};
        const controller=grouped?{open:groupOpen,close:groupClose,toggle:(reason,event)=>opened?groupClose(reason,event):groupOpen(reason,event),reposition:reason=>{const visual=record.visualTrigger;return!visual?false:visual.reposition(reason||'api');},getState:()=>({open:opened})}:null;
        if(grouped){rebuildGroupInteraction();this.adoptPopupRuntime(controller,{reference,popup:record.panel,owned:false});this.own(()=>{if(groupLease)groupLease.release();groupLease=null;});}else{syncOwnView(true);triggerSession=createIndependentTrigger();this.adoptPopupRuntime(triggerSession,{reference,popup:record.panel,owned:true});this.own(()=>DOM.removeNode(record.panel));}
        this.own(()=>{if(interaction){interaction.destroy();interaction=null;}});this.own(()=>{if(pointerMoveCleanup){pointerMoveCleanup();pointerMoveCleanup=null;}});
        rebuildPointerTracking();
        runtime.setContent=value=>{if(this.destroyed)return this;this.updateOptions({content:value});return this;};
        runtime.syncOptions=patch=>{const o=this.options,contentChanged=own(patch,'content'),interactionChanged=['trigger','openDelay','closeDelay','disabled','interactiveBorder','interactiveDebounce'].some(key=>own(patch,key)),cursorChanged=own(patch,'followCursor');normalizeTriggers(o.trigger);if(contentChanged&&o.fresh!==true&&!opened)contentDirty=true;if(cursorChanged){resetCursor();rebuildPointerTracking();}if(grouped){if(interactionChanged)rebuildGroupInteraction();if(record.activeMember===member)syncGroupVisual();}else{triggerSession.updateOptions(Object.assign(commonTriggerOptions(),{trigger:o.trigger,openDelay:o.openDelay,closeDelay:o.closeDelay,interactiveBorder:o.interactiveBorder,interactiveDebounce:o.interactiveDebounce}));if(!contentChanged||o.fresh===true||opened)syncOwnView(true);}if(own(patch,'open'))this.setOpen(o.open===true,'update-options');else if(o.disabled===true&&opened)this.close('disabled');else if(opened)this.reposition('options');};
        if(opts.open===true)this.open('initial');return ownerRoot;
    }

    [componentHooks.optionsUpdated](opts,previous,patch){requireState(this).syncOptions(patch);}
    [componentHooks.beforeDestroy](){const r=requireState(this);if(r.opened)this.close('tooltip-destroy');}
    setContent(value){return requireState(this).setContent(value);}
    getState(){const r=requireState(this),o=this.options,visual=r.grouped?r.record.visualTrigger:r.triggerSession,triggerState=visual?visual.getState():null;return Object.freeze({open:r.opened,disabled:o.disabled===true,trigger:normalizeTriggers(o.trigger).join(' '),placement:o.placement,size:o.size,fresh:o.fresh===true,contentDirty:r.contentDirty,destroyOnClose:o.destroyOnClose!==false,grouped:r.grouped,group:r.group,singletonActive:r.grouped&&r.record.activeMember===r.member,followCursor:o.followCursor,inlinePositioning:o.inlinePositioning===true,physicalOpen:!!(triggerState&&triggerState.open),destroyed:this.destroyed});}
    getTrigger(){const r=requireState(this);return r.grouped?r.record.visualTrigger:r.triggerSession;}
}
