import { Utils } from '../utils/utils.js';
var NULLABLE_FUNCTION = Object.freeze({ type: 'function', nullable: true });
var NULLABLE_OBJECT = Object.freeze({ type: 'object', nullable: true });
var BOOLEAN_OPTIONS = Object.freeze(new Set([
  'disabled','readOnly','required','clearable','open','destroyOnClose','busy','autoUpdate','flipOnOverflow','matchReferenceWidth',
  'multiple','searchable','closeOnSelect','checkable','showLine','keyboard','draggable','autoplay','arrows','dots','loop','focusTrap',
  'lockScroll','showMask','closable','forceRender','autoFocus','restoreFocus','centered','stretch','editable','addable','ghost','bordered',
  'accordion','destroyInactive','showArrow','followCursor','closeOnEscape','closeOnOutsidePress','closeOnMask','closeOnClick','closeOnTabExit',
  'interactive','loading','error','half','clearOnSelect','hideDisabledOptions','showSecond','use12Hours','needConfirm','showCancel','showNow','fixedLayout','stickyHeader','stickySummary','keepStaleData','forceRenderExpanded','preserveSelectedKeys',
  'commitInputOnBlur','preserveInvalidOnBlur','order','oneWay','sortable','searchable','openFileDialogOnClick','pastable','previewable',
  'removable','retryable','downloadable','autoUpload','multiple','directory','drag','dragSort','showList','hideTrigger','hideTriggerAtMax',
  'checkStrictly','changeOnSelect','closeOnSelect','highlightFirst','backfill','matchOnly','adaptiveHeight','pauseOnFocus','pauseOnHover',
  'swipe','waitForAnimate','circle','rounded','lazy','wheelZoom','doubleClickZoom','maskClosable','changeOnWheel','changeOnBlur','stringMode',
  'controls','keyboard','keyboardActivation','showProgress','pauseOnHover','closeOnClick','collapsed','edgeShadow','wheelPropagation','focusable','snapOnIdle','snapLoop'
]));
var NUMBER_OPTIONS = Object.freeze(new Set([
  'openDelay','closeDelay','duration','enterDuration','leaveDuration','moveDuration','interval','overscan','itemSize','visibleItemCount',
  'snapDuration','scrollIdleDelay','swipeThreshold','scaleStep','rotateStep','minScale','maxScale','precision','step','minChars','maxCount',
  'maxTagLength','maxVisible','inputMinWidth','overflowMaxHeight','hourStep','minuteStep','secondStep','panelCount','weekStartsOn','zIndex',
  'arrowPadding','interactiveBorder','interactiveDebounce','submenuLeaveDelay','submenuOffset','submenuOpenDelay','offset','indent','count','length'
]));
var ARRAY_OPTIONS = Object.freeze(new Set([
  'items','columns','buttons','actions','middleware','presets','pageSizeOptions','tokenSeparators','loadedKeys','expandedKeys','defaultExpandedKeys',
  'files','titles','allowEmpty','sorters','filters'
]));
var OBJECT_OPTIONS = Object.freeze(new Set(['classNames','classes','styles','elements','style','stackStyle','attrs','closeOptions','autoUpdateOptions','inlinePositioningOptions']));
var STRING_OPTIONS = Object.freeze(new Set(['className','name','placeholder','placement','size','status','strategy','variant','trigger','type','direction','orientation','selection','separator','rangeSeparator','easing','responsiveMode']));
function inferRule(key) {
  if (key === 'renderControl') return 'boolean';
  if (key === 'tokenSeparators') return Object.freeze({ types: Object.freeze(['array','function']), nullable: true });
  if (key === 'offset' || key === 'submenuOffset') return Object.freeze({ types: Object.freeze(['number','object','function']), nullable: true });
  if (/^(?:on|before|after|render|get|is)[A-Z]/.test(key)) return NULLABLE_FUNCTION;
  if (key === 'document') return 'document';
  if (BOOLEAN_OPTIONS.has(key)) return 'boolean';
  if (NUMBER_OPTIONS.has(key)) return 'number';
  if (ARRAY_OPTIONS.has(key)) return 'array';
  if (OBJECT_OPTIONS.has(key)) return NULLABLE_OBJECT;
  if (STRING_OPTIONS.has(key)) return 'string';
  return 'any';
}
function schema(keys) { var output = Object.create(null); keys.forEach(function (key) { output[key] = inferRule(key); }); return Object.freeze(output); }
function schemaWith(keys, overrides) { var output = Utils.assignOwn(Object.create(null), schema(keys), overrides || {}); return Object.freeze(output); }
function durationPairValue(value) { return (typeof value === 'number' && Number.isFinite(value)) || (Array.isArray(value) && value.length <= 2 && value.every(function (item) { return typeof item === 'number' && Number.isFinite(item); })); }
function autoFocusValue(value) { return value === false || typeof value === 'string' || typeof value === 'function' || !!(value && value.nodeType === 1); }
var contracts = {
  "Autocomplete": Object.freeze({ schema: schema(["applySuggestion","autoUpdate","backfill","busy","classNames","classes","clearable","closeDelay","container","defaultValue","destroyOnClose","disabled","document","elements","emptyText","error","errorText","filterItem","flipOnOverflow","focusOutline","formField","formTarget","getKey","getLabel","getSuggestionQuery","getValue","headless","height","highlightFirst","inputTarget","isItemDisabled","itemRender","itemSize","items","loadSuggestions","loadingText","matchOnly","matchReferenceWidth","maxHeight","middleware","minChars","name","onActiveChange","onBackfill","onBlur","onChange","onClear","onFocus","onInput","onOpenChange","onSearch","onSelect","onSuggestionsError","onSuggestionsLoad","onValueChange","open","openDelay","overscan","placeholder","placement","portalContainer","prefix","readOnly","reference","renderControl","required","setSelectionRange","size","sortItems","source","status","strategy","styles","suffix","trigger","triggerTarget","value","valueTarget","variant","virtual","virtualThreshold"]), legacy: Object.freeze(["options","triggerOnFocus","openOnFocus","defaultActiveFirstOption","filterOption","dataSource","fetchSuggestions","valueRender","draftValueRender"]), allowUnknown: false }),
  "Carousel": Object.freeze({ schema: schema(["adaptiveHeight","afterChange","arrows","autoplay","beforeChange","cardHeight","className","classNames","classes","container","direction","disabled","document","dotPlacement","dots","draggable","duration","easing","effect","elements","formField","formTarget","initialIndex","inputTarget","interval","items","keyboard","loop","name","nextArrow","onChange","pauseOnFocus","pauseOnHover","portalContainer","prevArrow","readOnly","reference","renderDot","required","source","styles","swipe","swipeThreshold","trigger","triggerTarget","type","valueTarget","waitForAnimate"]), legacy: Object.freeze(["target","el","mount","type","current","defaultCurrent","slides","speed","autoplaySpeed","indicatorPosition","arrow","infinite","initialSlide"]), allowUnknown: false }),
  "Cascader": Object.freeze({ schema: schema(["autoUpdate","busy","changeOnSelect","checkedStrategy","classNames","classes","clearable","closeDelay","closeOnSelect","container","defaultValue","destroyOnClose","disabled","document","elements","expandTrigger","filterPath","focusOutline","formField","formTarget","headless","height","inputTarget","itemRender","itemStyles","items","key","loadChildren","loadedKeys","matchReferenceWidth","maxHeight","maxVisibleTags","middleware","multiple","name","onChange","onClear","onLoad","onLoadError","onOpenChange","onSearch","onSelect","onValueChange","open","openDelay","placeholder","placement","popupRender","portalContainer","prefix","readOnly","reference","renderControl","renderPath","renderTag","renderTagOverflow","required","searchable","selectionAppearance","separator","size","source","status","strategy","styles","suffix","tagClasses","tagStyles","trigger","triggerTarget","value","valueTarget","variant","virtual","virtualThreshold"]), allowUnknown: false }),
  "Collapse": Object.freeze({ schema: schema(["accordion","animation","beforeChange","bordered","classNames","classes","collapsible","container","defaultValue","destroyInactive","disabled","document","elements","formField","formTarget","ghost","indicatorPosition","inputTarget","items","name","onChange","portalContainer","readOnly","reference","renderIndicator","required","size","source","styles","transition","triggerTarget","value","valueTarget"]), legacy: Object.freeze(["target","el","mount","activeKey","activeKeys","defaultActiveKey","defaultActiveKeys","destroyInactivePanel","expandIconPosition","ghosted"]), allowUnknown: false }),
  "ColorPicker": Object.freeze({ schema: schema(["angle","beforeClose","beforeOpen","busy","cancelText","classNames","classes","clearable","closeDelay","closeOnEscape","closeOnOutsidePress","confirmDisabled","confirmText","container","createDOM","defaultPickerValue","defaultValue","destroyOnClose","disabled","document","draftValueTarget","elements","eyeDropper","focusOutline","footer","footerEnd","footerStart","formField","formTarget","format","gradient","gradientAngle","headless","indicatorPlacement","inputTarget","keyboard","mode","name","needConfirm","onChange","onChangeComplete","onClear","onDraftChange","onError","onFormatChange","onInput","onInvalid","onOpenChange","onValueChange","open","openDelay","placeholder","placement","portalContainer","prefix","presets","readOnly","reference","renderControl","required","showAlpha","showCancel","size","source","status","stops","styles","suffix","swatchOnly","trigger","triggerTarget","value","valueTarget","variant"]), legacy: Object.freeze(["el","mount","allowClear","defaultOpen","colorFormat","predefine","picker","valueRender","draftValueRender"]), allowUnknown: false }),
  "DatePicker": Object.freeze({ schema: schema(["allowEmpty","beforeClose","beforeOpen","busy","cancelText","classNames","classes","clearable","closeDelay","closeOnEscape","closeOnOutsidePress","closeOnSelect","commitInputOnBlur","confirmDisabled","confirmText","container","createDOM","defaultPickerValue","defaultValue","destroyOnClose","disabled","disabledDate","disabledTime","document","draftValueTarget","elements","focusOutline","footer","footerEnd","footerStart","formField","formTarget","format","headless","hour","inputTarget","maxDate","minDate","minute","multipleSeparator","name","needConfirm","onChange","onClear","onDraftChange","onInput","onOpenChange","onPanelChange","onPreset","onPreviewChange","onSelect","onValueChange","open","openDelay","order","panelCount","panelRender","parseInput","pickerValue","placeholder","placement","portalContainer","prefix","preserveInvalidOnBlur","presets","previewValue","rangeSeparator","readOnly","reference","renderCell","renderControl","required","second","selection","showCancel","size","source","status","styles","suffix","time","trigger","triggerTarget","unit","value","valueTarget","variant","weekStartsOn"]), legacy: Object.freeze(["el","mount","allowClear","defaultOpen","mode","picker","range","multiple","showTime","timeOptions","type","separator","valueRender","draftValueRender"]), allowUnknown: false }),
  "Drawer": Object.freeze({ schema: schemaWith(["afterOpenChange","animation","attrs","autoFocus","autoLoading","autoOpen","buttonType","buttons","cancelText","className","classNames","classes","closable","closeIcon","closeOnClick","closeOnEscape","closeOnMask","closeOptions","confirmText","container","content","destroyOnHidden","disabled","document","duration","easing","elements","enterDuration","enterEasing","focusTrap","footer","forceRender","formField","formTarget","header","height","href","id","inputTarget","key","leaveDuration","leaveEasing","lockScroll","maskClassName","maskColor","maskStyle","name","onBeforeClose","onBeforeOpen","onCancel","onClick","onClose","onConfirm","onDestroy","onOpen","onOpenChange","placement","portalContainer","readOnly","reference","rel","required","respectReducedMotion","restoreFocus","role","scrollbarVisibility","showMask","source","style","styles","target","title","triggerTarget","type","valueTarget","width","zIndex"], { duration: durationPairValue, autoFocus: autoFocusValue, closable: Object.freeze({ types: Object.freeze(["boolean","object"]), nullable: true }) }), legacy: Object.freeze(["target","el","mount","visible","defaultVisible","getContainer","popupContainer"]), allowUnknown: false }),
  "Dropdown": Object.freeze({ schema: schemaWith(["arrowPadding","autoUpdate","beforeClose","beforeOpen","classNames","classes","closeDelay","closeOnEscape","closeOnOutsidePress","closeOnSelect","container","defaultValue","destroyOnClose","disabled","document","elements","flipOnOverflow","focusOnOpen","formField","formTarget","inputTarget","items","middleware","multiple","name","offset","onAction","onActiveChange","onChange","onClose","onOpen","onOpenChange","onSearch","onSelect","open","openDelay","placement","portalContainer","readOnly","reference","required","searchValue","searchable","selectable","selectionAppearance","showArrow","size","source","strategy","style","styles","submenuLeaveDelay","submenuOffset","submenuOpenDelay","submenuTrigger","trigger","triggerTarget","value","valueTarget"], { submenuOffset: Object.freeze({ types: Object.freeze(["number","object","function"]), nullable: true }) }), legacy: Object.freeze(["target","targetEl","triggerTarget","triggerEl","visible","defaultVisible","popupVisible","defaultPopupVisible","autoOpen","position","mouseEnterDelay","mouseLeaveDelay","destroyOnHidden","selectedValue","selectedValues","defaultValues","selectionMode","mode","type","options"]), allowUnknown: false }),
  "Image": Object.freeze({ schema: schema(["alt","circle","classNames","classes","container","controls","destroyOnClose","disabled","document","doubleClickZoom","draggable","elements","errorContent","fallback","fit","formField","formTarget","height","initialIndex","inputTarget","items","keyboard","lazy","maskClosable","maskColor","maskOpacity","maxScale","minScale","name","onDownload","onError","onFallback","onLoad","onPreviewChange","onPreviewVisibleChange","onTransform","placeholder","portalContainer","preview","previewGroup","previewList","previewMask","previewMaskText","readOnly","reference","required","rotateStep","rounded","scaleStep","source","src","styles","trajectory","triggerTarget","valueTarget","wheelZoom","width","zIndex"]), allowUnknown: false }),
  "InputNumber": Object.freeze({ schema: schemaWith(["changeOnBlur","changeOnWheel","classNames","classes","container","controls","decimalSeparator","defaultValue","disabled","document","elements","focusOutline","formField","formTarget","formatter","inputMode","inputTarget","keyboard","max","min","mode","name","onBlur","onChange","onFocus","onInput","onPressEnter","onStep","parser","placeholder","portalContainer","precision","prefix","readOnly","reference","required","size","source","status","step","stringMode","styles","suffix","target","triggerTarget","value","valueTarget","variant"], { step: Object.freeze({ types: Object.freeze(["number","string"]), nullable: true }) }), legacy: Object.freeze(["el","mount","controlPlacement"]), allowUnknown: false }),
  "InputOTP": Object.freeze({ schema: schemaWith(["accept","autoFocus","autocomplete","classNames","classes","container","defaultValue","disabled","document","elements","focusOutline","formField","formTarget","formatter","inputMode","inputTarget","length","mask","name","onBlur","onChange","onComplete","onFocus","onInput","placeholder","portalContainer","readOnly","reference","required","separator","size","source","status","styles","target","triggerTarget","value","valueTarget","variant"], { separator: Object.freeze({ types: Object.freeze(["string","function"]), nullable: true }), placeholder: Object.freeze({ types: Object.freeze(["string","array"]), nullable: true }) }), legacy: Object.freeze(["el","mount","allowedChars","type","allowClear","segments"]), allowUnknown: false }),
  "JSON": Object.freeze({ schema: schema(["addEventListener","autocomplete","className","classNames","classes","collapsed","container","copy","data","disabled","document","editable","elements","formField","formTarget","height","indent","inputTarget","maxDepth","maxHeight","name","onChange","portalContainer","readOnly","reference","required","showLine","size","sortKeys","source","spellcheck","styles","tabIndex","toolbar","triggerTarget","type","value","valueTarget","virtual","virtualThreshold"]), allowUnknown: false }),
  "Loading": Object.freeze({ schema: Object.freeze({ target: 'element', fullscreen: 'boolean', open: 'boolean', delay: 'number', text: 'any', indicator: 'any', size: { enum: ['xs','sm','md','lg','xl'] }, progress: 'any', showMask: 'boolean', lockScroll: 'boolean', blocking: 'boolean', className: 'string', style: 'object', boxStyle: 'object', maskColor: 'string', maskBlur: 'any', onOpen: 'function', onClose: 'function' }), legacy: Object.freeze(["el","mount","container","appendTo","triggerElement","triggerEl","visible","autoOpen","forceRender","keepMounted","destroyOnHidden","autoClose","openReason","event","_event","tip"]), allowUnknown: false }),
  "Menu": Object.freeze({ schema: schemaWith(["autoUpdate","className","classNames","classes","collapsed","collapsedWidth","container","defaultOpenKeys","destroyOnClose","disabled","disabledOverflow","document","elements","expandIcon","flipOnOverflow","forceSubMenuRender","formField","formTarget","inlineIndent","inputTarget","itemDisplay","items","loop","middleware","mode","multiple","name","onClick","onDeselect","onNavigate","onOpenChange","onSelect","onSelectedKeyChange","onSelectedKeysChange","onTitleClick","openKeys","overflowedIndicator","placement","portalContainer","querySelector","readOnly","reference","required","selectable","selectedKey","selectedKeys","selectionAppearance","size","source","strategy","style","styles","submenuLeaveDelay","submenuMode","submenuOffset","submenuOpenDelay","submenuTrigger","theme","tooltip","triggerTarget","valueTarget"], { submenuOffset: Object.freeze({ types: Object.freeze(["number","object","function"]), nullable: true }) }), allowUnknown: false }),
  "Message": Object.freeze({ schema: schema(["actions","className","classNames","classes","closable","closeOnClick","container","content","disabled","document","duration","easing","elements","enterDuration","formField","formTarget","icon","inputTarget","key","leaveDuration","maxCount","moveDuration","name","onBeforeClose","onClose","onOpen","onUpdate","pauseOnHover","pauseOnHoverScope","placement","portalContainer","readOnly","reference","required","showProgress","source","stack","stackClassName","stackStyle","style","styles","triggerTarget","type","valueTarget","zIndex"]), allowUnknown: false }),
  "Modal": Object.freeze({ schema: schemaWith(["afterClose","afterOpenChange","animation","attrs","autoFocus","autoLoading","autoOpen","buttonType","buttons","cancelText","center","className","classNames","classes","closable","closeIcon","closeOnClick","closeOnEscape","closeOnMask","closeOptions","confirmText","container","content","destroyOnHidden","disabled","document","duration","elements","enterDuration","focusTrap","footer","forceRender","formField","formTarget","fullscreen","header","href","id","inputTarget","key","label","leaveDuration","lockScroll","maskAnimation","maskBlur","maskClassName","maskColor","maskDuration","maskEnterDuration","maskLeaveDuration","maskStyle","maxWidth","name","onBeforeClose","onBeforeOpen","onCancel","onClick","onClose","onConfirm","onDestroy","onOpen","onOpenChange","origin","placement","portalContainer","readOnly","reference","rel","required","restoreFocus","role","scrollbarVisibility","showMask","source","style","styles","target","text","title","triggerTarget","type","valueTarget","width","zIndex"], { duration: durationPairValue, maskDuration: durationPairValue, maskEnterDuration: 'number', maskLeaveDuration: 'number', autoFocus: autoFocusValue, closable: Object.freeze({ types: Object.freeze(["boolean","object"]), nullable: true }) }), allowUnknown: false }),
  "Notification": Object.freeze({ schema: schema(["actions","className","classNames","classes","closable","closeOnClick","container","content","disabled","document","duration","easing","elements","enterDuration","formField","formTarget","icon","inputTarget","key","leaveDuration","maxCount","maxWidth","minWidth","moveDuration","name","onAction","onBeforeClose","onClose","onOpen","onUpdate","pauseOnHover","pauseOnHoverScope","placement","portalContainer","readOnly","reference","required","showProgress","source","stack","stackClassName","stackStyle","style","styles","title","triggerTarget","type","valueTarget","width","zIndex"]), allowUnknown: false }),
  "Pagination": Object.freeze({ schema: schema(["background","className","classNames","classes","components","container","count","current","disabled","document","elements","ellipsis","ellipsisJump","first","formField","formTarget","hideOnSinglePage","inputMode","inputTarget","itemRender","jump","last","layout","name","next","onChange","onNextClick","onPrevClick","onRender","onSizeChange","pageSize","pageSizeOptions","pagerCount","portalContainer","prev","readOnly","reference","required","responsive","showJumper","showSizeChanger","showTotal","simple","size","source","styles","triggerTarget","type","value","valueTarget"]), legacy: Object.freeze(["target","el","mount","element","total","limit","limits","defaultCurrent","step","pageCount","currentPage","pageSizes","small","showFirst","showLast","prevText","nextText","onPageChange","onCurrentChange","hash","theme","min"]), allowUnknown: false }),
  "Popconfirm": Object.freeze({ schema: schema(["arrowPadding","beforeClose","beforeOpen","cancelDisabled","cancelText","classNames","classes","closeDelay","closeOnEscape","closeOnFocusOutside","closeOnOutsidePress","closeOnTabExit","confirmDisabled","confirmText","container","content","danger","destroyOnClose","disabled","document","elements","formField","formTarget","icon","inputTarget","middleware","name","offset","onCancel","onClose","onConfirm","onConfirmError","onOpen","open","openDelay","originalEvent","placement","portalContainer","readOnly","reference","required","restoreFocus","restoreFocusOnClose","showArrow","showWarning","size","source","strategy","styles","title","trigger","triggerTarget","valueTarget"]), legacy: Object.freeze(["target","targetEl","triggerTarget","triggerEl","visible","defaultVisible","popupVisible","defaultPopupVisible","position","message","iconName","iconText","okText","okType","cancelButtonProps","okButtonProps"]), allowUnknown: false }),
  "Popover": Object.freeze({ schema: schema(["action","arrowPadding","autoUpdate","beforeClose","beforeOpen","classNames","classes","closeDelay","closeOnEscape","closeOnFocusOutside","closeOnOutsidePress","closeOnTabExit","container","containsTarget","content","destroyOnClose","disabled","document","elements","focusScope","formField","formTarget","inputTarget","middleware","name","offset","onClose","onOpen","onOpenChange","open","openDelay","placement","portalContainer","readOnly","reference","required","restoreFocus","restoreFocusOnClose","showArrow","size","source","strategy","styles","title","trigger","triggerTarget","valueTarget"]), legacy: Object.freeze(["target","targetEl","triggerTarget","triggerEl","anchor","anchorEl","visible","defaultVisible","popupVisible","defaultPopupVisible","autoOpen","position","contentNode","html","unmountOnExit","autoFitPosition","autoFixPosition","popupWidth","popupMinWidth","popupMaxWidth","popupStyle","panelStyle"]), allowUnknown: false }),
  "Progress": Object.freeze({ schema: schema(["classNames","classes","color","container","direction","disabled","document","elements","formField","formTarget","format","gapDegree","gapPlacement","inputTarget","name","onChange","onUpdate","percent","portalContainer","railColor","readOnly","reason","reference","required","showInfo","silent","size","source","status","steps","strokeColor","strokeLinecap","strokeWidth","styles","success","triggerTarget","type","valueTarget"]), legacy: Object.freeze(["target","el","mount","successPercent","successColor","trailColor"]), allowUnknown: false }),
  "Rate": Object.freeze({ schema: schema(["character","classNames","classes","clearable","container","count","defaultValue","direction","disabled","document","elements","formField","formTarget","half","inputTarget","keyboard","mode","name","onChange","onHoverChange","originalEvent","portalContainer","readOnly","reason","reference","required","serializeValue","silent","size","source","styles","toggle","tooltips","triggerTarget","user","value","valueTarget"]), legacy: Object.freeze(["el","mount","allowHalf","allowClear"]), allowUnknown: false }),
  "Result": Object.freeze({ schema: schemaWith(["classNames","classes","container","disabled","document","elements","extra","formField","formTarget","icon","inputTarget","name","portalContainer","readOnly","reference","required","size","source","styles","subtitle","title","triggerTarget","valueTarget","viewBox","visible"], { size: Object.freeze({ types: Object.freeze(["string","number"]), nullable: true }) }), legacy: Object.freeze(["target","el","show","status"]), allowUnknown: false }),
  "Ripple": Object.freeze({ schema: schema(["inside","outside","color"]), legacy: Object.freeze(["target","el","element","container","mount"]), allowUnknown: false }),
  "Scroll": Object.freeze({ schema: schema(["align","axis","behavior","classNames","classes","container","content","disabled","document","edgeShadow","edgeShadowSize","elements","focusable","formField","formTarget","inputTarget","keyboard","name","offset","onScroll","onScrollEnd","onScrollStart","onSnapSettle","portalContainer","readOnly","reason","reference","required","root","scrollIdleDelay","scrollbarHideDelay","scrollbarInteractive","scrollbarVisibility","snapAlign","snapAxis","snapBehavior","snapDuration","snapLoop","snapOnIdle","snapTargets","source","styles","triggerTarget","valueTarget","viewport","wheelAxis","wheelBehavior","wheelPropagation","x","y"]), legacy: Object.freeze(["target","el","mount","scrollX","scrollY","scrollbar","wrapper","wrap","view","scrollElement","virtual","virtualData","itemHeight","estimatedItemSize","wheelStepInterval","direction"]), allowUnknown: false }),
  "Select": Object.freeze({ schema: schemaWith(["addOnBlur","addOnEnter","addOnTab","autoUpdate","busy","classNames","classes","clearContent","clearSearchOnSelect","clearable","closeDelay","container","creatable","defaultActiveFirstOption","defaultValue","destroyOnClose","disabled","document","elements","emptyText","error","errorText","filterItem","flipOnOverflow","focusOutline","formField","formTarget","getKey","getLabel","getValue","headless","height","hideSelectedOptions","inputTarget","isItemDisabled","itemRender","itemSize","itemStyles","items","loading","loadingIcon","loadingText","matchReferenceWidth","maxCount","maxHeight","maxTagLength","maxVisibleTags","measureAvailableWidth","measureTagOverflowWidth","measureTagWidth","middleware","multiple","name","normalizeTag","onActive","onActiveChange","onBlur","onChange","onClear","onDeselect","onFocus","onInputKeyDown","onOpenChange","onPopupScroll","onSearch","onSelect","onTagInvalid","onValueChange","open","openDelay","overscan","placeholder","placement","popupRender","portalContainer","prefix","readOnly","reference","renderControl","renderTag","renderTagOverflow","renderValue","required","searchFields","searchable","selectionAppearance","size","sortItems","source","status","strategy","styles","suffix","tagClasses","tagInputMinWidth","tagRemoveContent","tagStyles","tagTextMaxLength","toggleContent","tokenSeparators","trigger","triggerTarget","validateTag","value","valueTarget","variant","virtual","virtualThreshold"], { tokenSeparators: Object.freeze({ types: Object.freeze(["array","function"]), nullable: true }) }), legacy: Object.freeze(["options","showSearch","allowClear","openOnFocus","mode","maxTagCount","tagRender","labelRender","valueRender","draftValueRender"]), allowUnknown: false }),
  "Slider": Object.freeze({ schema: schema(["allowCross","classNames","classes","container","defaultValue","disabled","document","dots","elements","final","formField","formTarget","handleDisabled","included","inputTarget","keyboard","marks","max","min","name","onAfterChange","onBeforeChange","onChange","onKeyDown","originalEvent","portalContainer","range","readOnly","reason","reference","required","reverse","serializeValue","silent","size","source","step","styles","tooltip","triggerTarget","user","value","valueTarget","vertical"]), legacy: Object.freeze(["el","mount","tipFormatter"]), allowUnknown: false }),
  "Sort": Object.freeze({ schema: schema(["animation","beforeMove","classNames","classes","container","disabled","document","draggable","elements","formField","formTarget","handleOnly","inputTarget","items","keyboard","name","onChange","onDragCancel","onDragEnd","onDragMove","onDragStart","orientation","originalEvent","portalContainer","readOnly","reason","reference","required","serializeValue","showActions","showHandle","silent","source","styles","triggerTarget","valueTarget"]), legacy: Object.freeze(["el","mount","mode","direction","itemSelector","handleSelector","dragHandle","handle","showButtons","handleText","preserveDom","clearOnDestroy","domMode","authored","modifierRequired","onBeforeMove","onSort"]), allowUnknown: false }),
  "Steps": Object.freeze({ schema: schema(["allowCurrentClick","className","classNames","classes","clickable","container","current","direction","disabled","document","elements","event","formField","formTarget","initial","inputTarget","itemRender","items","key","labelPlacement","name","notifySame","onChange","originalEvent","percent","portalContainer","progressDot","readOnly","reason","reference","required","responsive","silent","size","source","status","styles","triggerTarget","type","valueTarget"]), legacy: Object.freeze(["target","el","mount"]), allowUnknown: false }),
  "Table": Object.freeze({ schema: schema(["addEventListener","bordered","borderless","caption","checked","className","classNames","classes","columns","columnReorder","container","disabled","document","editEnterBehavior","elements","emptyText","errorText","expandedKeys","filteredTotal","filters","fixedLayout","footer","footerEnd","footerStart","forceRenderExpanded","formField","formTarget","getKey","height","hover","inputTarget","isItemDisabled","items","keepStaleData","key","keyboardNavigation","load","loading","loadingText","maxHeight","minWidth","name","onChange","onColumnReorder","onColumnResize","onColumnResizeEnd","onLoad","onLoadError","onRow","onRowClick","onRowDoubleClick","onRowContextMenu","onRowReorder","onSearchChange","onSelectionChange","overscan","page","pageSize","pager","portalContainer","preserveSelectedKeys","readOnly","reference","remoteSelectionScope","renderExpanded","required","rowClassName","rowExpandable","rowHeight","rowReorder","responsiveMode","searchMatcher","searchValue","selectedKeys","selectionMode","setSelectionRange","scrollPolicy","shadow","size","sortKey","sortOrder","source","stickyHeader","stickySummary","striped","styles","summary","tabIndex","title","toolbar","toolbarEnd","toolbarStart","total","triggerTarget","type","value","valueTarget","virtual","virtualThreshold"]), legacy: Object.freeze(["target","el","mount","dataSource","rowKey","rowSelection","expandable","pagination"]), allowUnknown: false }),
  "Tabs": Object.freeze({ schema: schema(["activationMode","activeKey","addable","animated","centered","className","classNames","classes","closable","container","createItem","defaultActiveKey","destroyInactive","disabled","document","edgeShadow","editable","elements","formField","formTarget","id","indicator","inputTarget","items","key","label","name","onAdd","onBeforeChange","onBeforeEdit","onChange","onEdit","orientation","overflow","overflowMaxHeight","overflowPopupRender","placement","portalContainer","readOnly","reference","required","size","source","stretch","styles","transition","triggerTarget","type","valueTarget","wheelPropagation"]), legacy: Object.freeze(["target","el","mount","position","tabPosition","active","defaultActive"]), allowUnknown: false }),
  "TagInput": Object.freeze({ schema: schema(["addOnBlur","addOnEnter","addOnTab","beforeAdd","beforeEdit","beforeRemove","classNames","classes","clearVisibility","clearable","container","creatable","defaultValue","disabled","document","elements","focusOutline","formField","formTarget","inputTarget","inputValue","js","maxTagLength","maxTags","name","normalizeTag","onAdd","onBlur","onChange","onEdit","onFocus","onInput","onInvalid","onKeydown","onRemove","placeholder","portalContainer","prefix","readOnly","reference","required","size","source","status","styles","suffix","tags","tokenSeparators","tokenizeOnPaste","triggerTarget","unique","validateTag","value","valueTarget","variant"]), legacy: Object.freeze(["el","mount","tags","defaultTags","allowClear","showSearch","searchable","hasPopup","showArrow","inputTag"]), allowUnknown: false }),
  "Tags": Object.freeze({ schema: schema(["addLabel","addOnBlur","addOnEnter","addOnTab","beforeAdd","beforeEdit","beforeRemove","checkable","className","classNames","classes","closable","container","controlled","creatable","defaultValue","disabled","document","editable","elements","formField","formTarget","hosted","inputMinWidth","inputTarget","inputValue","items","maxCount","maxTagLength","maxVisible","measureAvailableWidth","measureItemWidth","measureOverflowWidth","multiple","name","normalizeTag","onAdd","onAddRequest","onBlur","onChange","onClose","onEdit","onFocus","onInput","onInvalid","onItemsChange","onKeydown","onOverflow","onRemove","onRemoveRequest","onSearch","overflow","overflowMaxHeight","overflowPlacement","overflowTrigger","placeholder","placement","portalContainer","readOnly","reference","renderOverflow","renderTag","required","scrollbarVisibility","showOverflowPopover","size","source","styles","tabIndex","tagClassName","tagOverflowClassName","tagRemoveClassName","tagRemoveContent","tagTextClassName","tokenSeparators","tokenizeOnPaste","triggerTarget","type","unique","validateTag","value","valueTarget","variant"]), legacy: Object.freeze(["nameInput","wrap","target","el","mount","options","checkedValue","checkedValues","defaultCheckedValues","maxTagCount","maxTagPlaceholder","overflowPopover","collapsedTooltip","minCollapsedNum"]), allowUnknown: false }),
  "TimePicker": Object.freeze({ schema: schema(["beforeClose","beforeOpen","busy","cancelText","cellRender","changeOnScroll","classNames","classes","clearable","closeDelay","closeOnEscape","closeOnOutsidePress","closeOnSelect","commitInputOnBlur","confirmDisabled","confirmText","container","createDOM","defaultPickerValue","defaultValue","destroyOnClose","disabled","disabledHours","disabledMinutes","disabledSeconds","disabledTime","document","draftValueTarget","elements","focusOutline","footer","footerEnd","footerStart","formField","formTarget","headless","hideDisabledOptions","hourStep","inputTarget","match","minuteStep","name","needConfirm","nowText","onChange","onClear","onDraftChange","onInput","onOpenChange","onPreviewChange","onSelect","onValueChange","open","openDelay","order","placeholder","placement","portalContainer","prefix","preserveInvalidOnBlur","previewValue","rangeSeparator","readOnly","reference","renderControl","required","secondStep","selection","showCancel","showNow","showSecond","size","source","status","styles","suffix","trigger","triggerTarget","use12Hours","value","valueTarget","variant"]), legacy: Object.freeze(["el","mount","allowClear","defaultOpen","picker","range","valueRender","draftValueRender"]), allowUnknown: false }),
  "Tooltip": Object.freeze({ schema: schema(["arrowPadding","autoUpdate","beforeClose","beforeOpen","classNames","classes","closeDelay","closeOnEscape","container","content","destroyOnClose","disabled","document","elements","followCursor","formField","formTarget","fresh","group","inlinePositioning","inlinePositioningOptions","inputTarget","interactiveBorder","interactiveDebounce","middleware","name","offset","onClose","onOpen","onOpenChange","open","openDelay","parentLayerId","placement","portalContainer","readOnly","reference","required","showArrow","size","source","strategy","styles","trigger","triggerTarget","unique","valueTarget","zIndex"]), legacy: Object.freeze(["target","targetEl","triggerTarget","triggerEl","anchor","anchorEl","visible","defaultVisible","popupVisible","defaultPopupVisible","autoOpen","position","title","mouseEnterDelay","mouseLeaveDelay","autoFitPosition"]), allowUnknown: false }),
  "Transfer": Object.freeze({ schema: schema(["checked","classNames","classes","columns","container","disabled","document","elements","filterItem","formField","formTarget","getKey","getLabel","getValue","height","indeterminate","inputTarget","isItemDisabled","itemRender","items","maxHeight","name","onChange","onPageChange","onRowClick","onSearch","oneWay","pagination","portalContainer","readOnly","reference","renderFooter","renderTitle","required","rowClassName","searchable","serializeValue","size","sortable","source","status","styles","table","titles","triggerTarget","type","value","valueTarget","virtual","virtualThreshold"]), legacy: Object.freeze(["targetKeys","dataSource","selectedKeys","sourceSelectedKeys","targetSelectedKeys"]), allowUnknown: false }),
  "TreeSelect": Object.freeze({ schema: schema(["add","autoUpdate","beforeCheck","beforeExpand","busy","checkStrictly","checkable","checkedStrategy","classNames","classes","clearable","closeDelay","closeOnSelect","container","defaultExpandedKeys","defaultValue","destroyOnClose","disabled","document","elements","expandedKeys","filterItem","flipOnOverflow","focusOutline","formField","formTarget","getItems","getKey","getLabel","getValue","has","headless","height","indent","inputTarget","isItemDisabled","itemRender","itemStyles","items","loadChildren","loadedKeys","matchReferenceWidth","maxCount","maxHeight","maxVisibleTags","middleware","multiple","name","onChange","onCheck","onClear","onExpand","onLoad","onLoadError","onOpenChange","onRemove","onSearch","onSelect","onValueChange","open","openDelay","placeholder","placement","popupRender","portalContainer","prefix","readOnly","reference","renderControl","renderIcon","renderTag","renderTagOverflow","required","searchable","showLine","size","source","status","strategy","styles","suffix","tagClasses","tagStyles","trigger","triggerTarget","value","valueTarget","variant","virtual","virtualThreshold"]), legacy: Object.freeze(["options","mode","showSearch","allowClear","openOnFocus","valueRender","draftValueRender"]), allowUnknown: false }),
  "Trigger": Object.freeze({ schema: schema(["afterClose","afterOpen","allowReferenceUpdate","applyPosition","arrow","arrowElement","arrowPadding","autoUpdate","autoUpdateOptions","beforeClose","beforeInfo","beforeOpen","classNames","classes","closeDelay","closeOnEscape","closeOnFocusOutside","closeOnOutsidePress","closeOnTabExit","compensateScrollbar","componentType","container","containsTarget","destroyOnClose","destroyOnDeactivate","disabled","document","elements","exclude","flipOnOverflow","floating","fallbackFocus","focusOnActivate","focusOnOpen","focusScope","forceRender","formField","formTarget","group","initialFocus","inlinePositioning","inlinePositioningOptions","inputTarget","interactiveBorder","interactiveDebounce","keyboardActivation","layerKind","lockScroll","manageZIndex","matchReferenceWidth","middleware","name","offset","onClose","onInteractionEnter","onInteractionLeave","onOpen","onOpenChange","onPositionError","onPositionUpdate","open","openDelay","parent","parentLayerId","placement","portalContainer","position","positionReference","readOnly","record","reference","required","restoreFocus","restoreFocusOnClose","restoreFocusOnDismiss","restoreFocusTarget","scrollLockTarget","setVisible","source","strategy","styles","tabExitTarget","transition","transitionElement","trapFocus","trigger","triggerTarget","useTransformPosition","valueTarget","wasOpen","zIndex"]), legacy: Object.freeze(["target","targetEl","triggerEl","anchor","anchorEl","popup","popupEl","panel","popupVisible","defaultPopupVisible","clickOutsideToClose","enterDelay","leaveDelay","mouseEnterDelay","mouseLeaveDelay","motion","bindTarget"]), allowUnknown: false }),
  "Upload": Object.freeze({ schema: schema(["abortable","accept","actionVisibility","autoUpload","beforeRemove","beforeUpload","capture","className","classNames","classes","click","container","defaultValue","directory","disabled","document","downloadable","drag","dragSort","dragText","dropHint","elements","files","formField","formTarget","format","hideTrigger","hideTriggerAtMax","inputName","inputTarget","itemRender","listType","maxCount","maxSize","multiple","name","onChange","onDownload","onDrop","onError","onPaste","onPreview","onPreviewChange","onPreviewVisibleChange","onProgress","onReject","onRemove","onSort","onSuccess","openFileDialogOnClick","pastable","portalContainer","previewFile","previewTarget","previewable","progressView","readOnly","reference","removable","removeAttribute","renderExtra","renderFileIcon","renderTrigger","request","required","retryable","serializeValue","setAttribute","showLabel","showList","source","styles","tabIndex","thickness","thumbUrl","transformFile","triggerTarget","triggerText","type","uid","value","valueTarget","zIndex"]), legacy: Object.freeze(["el","mount","fileList","defaultFileList","customRequest","action","showUploadList","renderItem","trigger","iconRender","isImageUrl","progress","maxCountHideTrigger","dragHint"]), allowUnknown: false }),
  "WheelPicker": Object.freeze({ schema: schema(["afterClose","afterOpen","beforeClose","beforeOpen","busy","cancelText","classNames","classes","clearable","closeDelay","closeOnEscape","closeOnOutsidePress","closeOnSelect","columns","commitMeta","confirmDisabled","confirmText","container","createDOM","defaultValue","destroyOnClose","disabled","document","draftValueTarget","elements","focusOutline","footer","footerEnd","footerStart","formField","formTarget","formatValue","headless","inputTarget","itemHeight","loop","matchReferenceWidth","name","needConfirm","onChange","onClear","onDraftChange","onOpenChange","onSelect","onValueChange","open","openDelay","panelSynced","placeholder","placement","portalContainer","prefix","readOnly","reference","renderControl","required","scrollIdleDelay","scrollbarVisibility","separator","showCancel","size","snapBehavior","snapDuration","source","status","styles","suffix","trigger","triggerTarget","value","valueTarget","variant","visibleItemCount","wheelPropagation"]), legacy: Object.freeze(["el","mount","allowClear","changeOnScroll","picker","genericPicker","pickerInstance","options","snapWheelMode","wheelStepInterval","valueRender","draftValueRender"]), allowUnknown: false })
};

function validateType(value, rule) {
    if (value === undefined) return true;
    if (rule === undefined || rule === null || rule === 'any') return true;
    if (Array.isArray(rule)) return rule.indexOf(value) >= 0;
    if (typeof rule === 'function') return rule(value) !== false;
    if (typeof rule === 'object') {
        if (rule.nullable === true && value == null) return true;
        if (rule.enum && rule.enum.indexOf(value) < 0) return false;
        if (Array.isArray(rule.types) && !rule.types.some(type => validateType(value, type))) return false;
        if (rule.type && !validateType(value, rule.type)) return false;
        return true;
    }
    if (rule === 'array') return Array.isArray(value);
    if (rule === 'element') return !!(value && value.nodeType === 1);
    if (rule === 'document') return !!(value && value.nodeType === 9 && typeof value.createElement === 'function');
    if (rule === 'object') return !!(value && typeof value === 'object' && !Array.isArray(value));
    if (rule === 'number') return typeof value === 'number' && Number.isFinite(value);
    return typeof value === String(rule);
}

function getContract(name) { return contracts[String(name || '')] || null; }

function validateContractOptions(contract, options, owner) {
    var input = options || {};
    if (!contract) return input;
    var label = String(owner || 'Component');
    (contract.legacy || []).forEach(function (legacy) {
        if (Object.prototype.hasOwnProperty.call(input, legacy)) throw new TypeError('[QXFRAME9A7C2] ' + label + ' does not accept legacy option "' + legacy + '".');
    });
    var schema = contract.schema || {};
    Object.keys(input).forEach(function (option) {
        if (contract.allowUnknown === false && !Object.prototype.hasOwnProperty.call(schema, option)) throw new TypeError('[QXFRAME9A7C2] ' + label + ' does not accept unknown option "' + option + '".');
        if (Object.prototype.hasOwnProperty.call(schema, option) && !validateType(input[option], schema[option])) throw new TypeError('[QXFRAME9A7C2] ' + label + ' option "' + option + '" has an invalid value.');
    });
    return input;
}

const contractNames = Object.freeze(Object.keys(contracts).sort());
export const ComponentContracts = Object.freeze({ names: contractNames, get: getContract, validate: validateContractOptions, validateType });
export { contractNames, getContract, validateContractOptions, validateType };
