import { FocusManager } from './focusManager.js';
import { FocusOrigin } from './focusOrigin.js';
import { FocusScope } from './focusScope.js';
import { KeyboardRegion } from './keyboardRegion.js';
import { KeyboardNavigation } from './keyboardNavigation.js';
import { Utils } from '../utils/utils.js';
function resolveElement(value){var node=Utils.isFunction(value)?value():value;return node&&node.nodeType===1?node:null;}
function normalizeOrigin(value,fallback){var origin=String(value||fallback||'programmatic').toLowerCase();return FocusOrigin.origins.indexOf(origin)>=0?origin:(fallback||'programmatic');}
function create(options){
  var settings=Utils.mergeOwn(options||{}),root=resolveElement(settings.root);if(!root)throw new TypeError('[QXFRAME9A7C2] FocusController root is required.');
  var documentRef=settings.document||root.ownerDocument||globalThis.document;FocusOrigin.setup(documentRef);
  var focusManager=settings.focusManager||FocusManager.create({document:documentRef}),ownsFocusManager=!settings.focusManager,ownsRegion=!settings.region,region=settings.region||KeyboardRegion.create(settings);
  var activeRegion=settings.activeRegion===undefined||settings.activeRegion===null?null:String(settings.activeRegion),returnTarget=settings.returnTarget||null,editLease=null,revision=0,destroyed=false,api=null;
  function setActiveRegion(next,meta){if(destroyed)return false;var normalized=next===undefined||next===null||next===''?null:String(next);if(normalized===activeRegion)return true;var previous=activeRegion;activeRegion=normalized;revision+=1;if(Utils.isFunction(settings.onRegionChange))settings.onRegionChange(activeRegion,Object.freeze({activeRegion,previousRegion:previous,source:meta&&meta.source||'api',reason:meta&&meta.reason||'region-change',originalEvent:meta&&meta.originalEvent||null,focusController:api}));return true;}
  function setReturnTarget(next){if(destroyed)return false;if(next!==null&&next!==undefined&&!Utils.isFunction(next)&&!(next&&next.nodeType===1))throw new TypeError('[QXFRAME9A7C2] FocusController returnTarget must be an Element, function, or null.');if(returnTarget===next)return true;returnTarget=next||null;revision+=1;return true;}
  function restoreFocus(options){if(destroyed)return false;var target=resolveElement(returnTarget);if(!target)return false;var local=Utils.mergeOwn({preventScroll:true},options||{});if(!local.origin)local.origin=FocusOrigin.inherited(documentRef);if(!local.source)local.source='focus-controller-restore';return focusManager.focus(target,local);}
  function beginEdit(target,meta){if(destroyed)return false;var editor=resolveElement(target);if(!editor)throw new TypeError('[QXFRAME9A7C2] FocusController edit lease requires an Element.');var local=meta||{},requestedOrigin=normalizeOrigin(local.origin||local.source,FocusOrigin.inherited(documentRef));if(editLease&&editLease.target===editor){if(documentRef&&documentRef.activeElement===editor)FocusOrigin.set(editor,requestedOrigin,{source:'focus-controller-edit-refresh',originalEvent:local.originalEvent||null});return editLease;}var previousFocus=FocusOrigin.capture(documentRef);editLease=Object.freeze({target:editor,region:activeRegion,source:local.source||'api',reason:local.reason||'edit-begin',origin:requestedOrigin,previousFocus});if(documentRef&&documentRef.activeElement===editor)FocusOrigin.set(editor,editLease.origin,{source:'focus-controller-edit-begin',originalEvent:local.originalEvent||null});else FocusOrigin.prepare(editor,editLease.origin,{source:'focus-controller-edit-begin'});revision+=1;return editLease;}
  function endEdit(meta){if(destroyed||!editLease)return false;var previous=editLease;editLease=null;revision+=1;if(meta&&meta.restore===true){var restoreOrigin=previous.origin||(previous.previousFocus&&previous.previousFocus.origin)||FocusOrigin.inherited(documentRef);focusManager.focus(root,{preventScroll:true,origin:restoreOrigin,source:meta.source||'focus-controller-edit-end'});}return true;}
  function bindVirtualFocus(options){if(destroyed)return null;var local=Utils.mergeOwn(options||{});if(!local.controller)local.controller=region.virtualFocus;local.region=region;local.keyboard=region.keyboard;if(!local.root)local.root=root;return KeyboardRegion.bindVirtualFocus(local);}
  function update(nextOptions){if(destroyed)return api;var next=nextOptions||{};if(Object.prototype.hasOwnProperty.call(next,'activeRegion'))setActiveRegion(next.activeRegion,{source:'options',reason:'active-region'});if(Object.prototype.hasOwnProperty.call(next,'returnTarget'))setReturnTarget(next.returnTarget);region.update(next);return api;}
  function getState(){var virtualState=region&&region.virtualFocus&&Utils.isFunction(region.virtualFocus.getState)?region.virtualFocus.getState():null;var active=documentRef&&documentRef.activeElement&&documentRef.activeElement.nodeType===1?documentRef.activeElement:null;var realFocusOwned=!!(active&&(active===root||(root.contains&&root.contains(active))));return Object.freeze({activeRegion,activeKey:virtualState&&virtualState.key||null,domain:virtualState&&virtualState.domain||null,modality:virtualState&&virtualState.modality||null,virtualFocusOrigin:virtualState&&virtualState.modality||null,realFocusOrigin:realFocusOwned?FocusOrigin.originOf(active):null,realFocusOwned,hosted:!!(region&&region.hosted===true),disabled:!!(region&&region.disabled===true),editLease,editLeaseActive:!!editLease,revision,destroyed});}
  function destroy(){if(destroyed)return false;destroyed=true;editLease=null;returnTarget=null;revision+=1;if(ownsRegion&&region)region.destroy();if(ownsFocusManager&&focusManager)focusManager.destroy();region=null;focusManager=null;return true;}
  api={keyboard:region.keyboard,virtualFocus:region.virtualFocus,getKeyboardRegion:()=>region,bindVirtualFocus,setActiveRegion,setReturnTarget,restoreFocus,beginEdit,endEdit,update,setHosted(value){if(!destroyed)region.setHosted(value===true);return api;},setDisabled(value){if(!destroyed)region.setDisabled(value===true);return api;},focus(focusOptions){return !destroyed&&region?region.focus(focusOptions):false;},getState,destroy};
  Object.defineProperties(api,{activeRegion:{enumerable:true,get:()=>activeRegion},activeKey:{enumerable:true,get:()=>getState().activeKey},hosted:{enumerable:true,get:()=>!!(region&&region.hosted)},disabled:{enumerable:true,get:()=>!!(region&&region.disabled)},destroyed:{enumerable:true,get:()=>destroyed}});return api;
}
export const FocusController=Object.freeze({create,bindVirtualFocus:KeyboardRegion.bindVirtualFocus,forwardHandlers:KeyboardRegion.forwardHandlers,shouldPreserveNativeTextEditing:KeyboardNavigation.shouldPreserveNativeTextEditing,createManager:FocusManager.create,createScope:FocusScope.create,normalizeScopeMode:FocusScope.normalizeMode}); export{create};
