// Generated from ComponentRuntime OptionSchema by tools/build.js. Do not edit by hand.
export interface QXComponentInstance { destroy(): boolean | void; updateOptions?(options: Record<string, unknown>): unknown; getRootElement?(): Element | null; }
export interface QXComponentApi<TOptions> { create(options?: TOptions): QXComponentInstance; enhance?(target: Element | string, options?: TOptions): QXComponentInstance; }

export interface AutocompleteOptions {
  "applySuggestion"?: unknown;
  "autoUpdate"?: boolean;
  "backfill"?: boolean;
  "busy"?: boolean;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "container"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "emptyText"?: unknown;
  "error"?: boolean;
  "errorText"?: unknown;
  "filterItem"?: unknown;
  "flipOnOverflow"?: boolean;
  "focusOutline"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "getKey"?: (...args: any[]) => any | null;
  "getLabel"?: (...args: any[]) => any | null;
  "getSuggestionQuery"?: (...args: any[]) => any | null;
  "getValue"?: (...args: any[]) => any | null;
  "headless"?: unknown;
  "height"?: unknown;
  "highlightFirst"?: boolean;
  "inputTarget"?: unknown;
  "isItemDisabled"?: (...args: any[]) => any | null;
  "itemRender"?: unknown;
  "itemSize"?: number;
  "items"?: unknown[];
  "loadSuggestions"?: unknown;
  "loadingText"?: unknown;
  "matchOnly"?: boolean;
  "matchReferenceWidth"?: boolean;
  "maxHeight"?: unknown;
  "middleware"?: unknown[];
  "minChars"?: number;
  "name"?: string;
  "onActiveChange"?: (...args: any[]) => any | null;
  "onBackfill"?: (...args: any[]) => any | null;
  "onBlur"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onFocus"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onSearch"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onSuggestionsError"?: (...args: any[]) => any | null;
  "onSuggestionsLoad"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "overscan"?: number;
  "placeholder"?: string;
  "placement"?: string;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderControl"?: boolean;
  "required"?: boolean;
  "setSelectionRange"?: unknown;
  "size"?: string;
  "sortItems"?: unknown;
  "source"?: unknown;
  "status"?: string;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
  "virtual"?: unknown;
  "virtualThreshold"?: unknown;
}

export interface CarouselOptions {
  "adaptiveHeight"?: boolean;
  "afterChange"?: (...args: any[]) => any | null;
  "arrows"?: boolean;
  "autoplay"?: boolean;
  "beforeChange"?: (...args: any[]) => any | null;
  "cardHeight"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "direction"?: string;
  "disabled"?: boolean;
  "document"?: Document;
  "dotPlacement"?: unknown;
  "dots"?: boolean;
  "draggable"?: boolean;
  "duration"?: number;
  "easing"?: string;
  "effect"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "initialIndex"?: unknown;
  "inputTarget"?: unknown;
  "interval"?: number;
  "items"?: unknown[];
  "keyboard"?: boolean;
  "loop"?: boolean;
  "name"?: string;
  "nextArrow"?: unknown;
  "onChange"?: (...args: any[]) => any | null;
  "pauseOnFocus"?: boolean;
  "pauseOnHover"?: boolean;
  "portalContainer"?: unknown;
  "prevArrow"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderDot"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "swipe"?: boolean;
  "swipeThreshold"?: number;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
  "waitForAnimate"?: boolean;
}

export interface CascaderOptions {
  "autoUpdate"?: boolean;
  "busy"?: boolean;
  "changeOnSelect"?: boolean;
  "checkedStrategy"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "closeOnSelect"?: boolean;
  "container"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "expandTrigger"?: unknown;
  "filterPath"?: unknown;
  "focusOutline"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "headless"?: unknown;
  "height"?: unknown;
  "inputTarget"?: unknown;
  "itemRender"?: unknown;
  "itemStyles"?: unknown;
  "items"?: unknown[];
  "key"?: unknown;
  "loadChildren"?: unknown;
  "loadedKeys"?: unknown[];
  "matchReferenceWidth"?: boolean;
  "maxHeight"?: unknown;
  "maxVisibleTags"?: unknown;
  "middleware"?: unknown[];
  "multiple"?: boolean;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onLoad"?: (...args: any[]) => any | null;
  "onLoadError"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onSearch"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "placeholder"?: string;
  "placement"?: string;
  "popupRender"?: unknown;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderControl"?: boolean;
  "renderPath"?: (...args: any[]) => any | null;
  "renderTag"?: (...args: any[]) => any | null;
  "renderTagOverflow"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "searchable"?: boolean;
  "selectionAppearance"?: unknown;
  "separator"?: string;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "tagClasses"?: unknown;
  "tagStyles"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
  "virtual"?: unknown;
  "virtualThreshold"?: unknown;
}

export interface CollapseOptions {
  "accordion"?: boolean;
  "animation"?: unknown;
  "beforeChange"?: (...args: any[]) => any | null;
  "bordered"?: boolean;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "collapsible"?: unknown;
  "container"?: unknown;
  "defaultValue"?: unknown;
  "destroyInactive"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "ghost"?: boolean;
  "indicatorPosition"?: unknown;
  "inputTarget"?: unknown;
  "items"?: unknown[];
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderIndicator"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "transition"?: unknown;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
}

export interface ColorPickerOptions {
  "angle"?: unknown;
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "busy"?: boolean;
  "cancelText"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnOutsidePress"?: boolean;
  "confirmDisabled"?: unknown;
  "confirmText"?: unknown;
  "container"?: unknown;
  "createDOM"?: unknown;
  "defaultPickerValue"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "draftValueTarget"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "eyeDropper"?: unknown;
  "focusOutline"?: unknown;
  "footer"?: unknown;
  "footerEnd"?: unknown;
  "footerStart"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "format"?: unknown;
  "gradient"?: unknown;
  "gradientAngle"?: unknown;
  "headless"?: unknown;
  "indicatorPlacement"?: unknown;
  "inputTarget"?: unknown;
  "keyboard"?: boolean;
  "mode"?: unknown;
  "name"?: string;
  "needConfirm"?: boolean;
  "onChange"?: (...args: any[]) => any | null;
  "onChangeComplete"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onDraftChange"?: (...args: any[]) => any | null;
  "onError"?: (...args: any[]) => any | null;
  "onFormatChange"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "onInvalid"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "placeholder"?: string;
  "placement"?: string;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "presets"?: unknown[];
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderControl"?: boolean;
  "required"?: boolean;
  "showAlpha"?: unknown;
  "showCancel"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "stops"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "swatchOnly"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
}

export interface DatePickerOptions {
  "allowEmpty"?: unknown[];
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "busy"?: boolean;
  "cancelText"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnOutsidePress"?: boolean;
  "closeOnSelect"?: boolean;
  "commitInputOnBlur"?: boolean;
  "confirmDisabled"?: unknown;
  "confirmText"?: unknown;
  "container"?: unknown;
  "createDOM"?: unknown;
  "defaultPickerValue"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "disabledDate"?: unknown;
  "disabledTime"?: unknown;
  "document"?: Document;
  "draftValueTarget"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "focusOutline"?: unknown;
  "footer"?: unknown;
  "footerEnd"?: unknown;
  "footerStart"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "format"?: unknown;
  "headless"?: unknown;
  "hour"?: unknown;
  "inputTarget"?: unknown;
  "maxDate"?: unknown;
  "minDate"?: unknown;
  "minute"?: unknown;
  "multipleSeparator"?: unknown;
  "name"?: string;
  "needConfirm"?: boolean;
  "onChange"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onDraftChange"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onPanelChange"?: (...args: any[]) => any | null;
  "onPreset"?: (...args: any[]) => any | null;
  "onPreviewChange"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "order"?: boolean;
  "panelCount"?: number;
  "panelRender"?: unknown;
  "parseInput"?: unknown;
  "pickerValue"?: unknown;
  "placeholder"?: string;
  "placement"?: string;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "preserveInvalidOnBlur"?: boolean;
  "presets"?: unknown[];
  "previewValue"?: unknown;
  "rangeSeparator"?: string;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderCell"?: (...args: any[]) => any | null;
  "renderControl"?: boolean;
  "required"?: boolean;
  "second"?: unknown;
  "selection"?: string;
  "showCancel"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "time"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "unit"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
  "weekStartsOn"?: number;
}

export interface DrawerOptions {
  "afterOpenChange"?: (...args: any[]) => any | null;
  "animation"?: unknown;
  "attrs"?: Record<string, unknown> | null;
  "autoFocus"?: unknown;
  "autoLoading"?: unknown;
  "autoOpen"?: unknown;
  "buttonType"?: unknown;
  "buttons"?: unknown[];
  "cancelText"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closable"?: boolean | Record<string, unknown> | null;
  "closeIcon"?: unknown;
  "closeOnClick"?: boolean;
  "closeOnEscape"?: boolean;
  "closeOnMask"?: boolean;
  "closeOptions"?: Record<string, unknown> | null;
  "confirmText"?: unknown;
  "container"?: unknown;
  "content"?: unknown;
  "destroyOnHidden"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "duration"?: unknown;
  "easing"?: string;
  "elements"?: Record<string, unknown> | null;
  "enterDuration"?: number;
  "enterEasing"?: unknown;
  "focusTrap"?: boolean;
  "footer"?: unknown;
  "forceRender"?: boolean;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "header"?: unknown;
  "height"?: unknown;
  "href"?: unknown;
  "id"?: unknown;
  "inputTarget"?: unknown;
  "key"?: unknown;
  "leaveDuration"?: number;
  "leaveEasing"?: unknown;
  "lockScroll"?: boolean;
  "maskClassName"?: unknown;
  "maskColor"?: unknown;
  "maskStyle"?: unknown;
  "name"?: string;
  "onBeforeClose"?: (...args: any[]) => any | null;
  "onBeforeOpen"?: (...args: any[]) => any | null;
  "onCancel"?: (...args: any[]) => any | null;
  "onClick"?: (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onConfirm"?: (...args: any[]) => any | null;
  "onDestroy"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "rel"?: unknown;
  "required"?: boolean;
  "respectReducedMotion"?: unknown;
  "restoreFocus"?: boolean;
  "role"?: unknown;
  "scrollbarVisibility"?: unknown;
  "showMask"?: boolean;
  "source"?: unknown;
  "style"?: Record<string, unknown> | null;
  "styles"?: Record<string, unknown> | null;
  "target"?: unknown;
  "title"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
  "width"?: unknown;
  "zIndex"?: number;
}

export interface DropdownOptions {
  "arrowPadding"?: number;
  "autoUpdate"?: boolean;
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnOutsidePress"?: boolean;
  "closeOnSelect"?: boolean;
  "container"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "flipOnOverflow"?: boolean;
  "focusOnOpen"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "inputTarget"?: unknown;
  "items"?: unknown[];
  "middleware"?: unknown[];
  "multiple"?: boolean;
  "name"?: string;
  "offset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "onAction"?: (...args: any[]) => any | null;
  "onActiveChange"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onSearch"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "searchValue"?: unknown;
  "searchable"?: boolean;
  "selectable"?: unknown;
  "selectionAppearance"?: unknown;
  "showArrow"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "strategy"?: string;
  "style"?: Record<string, unknown> | null;
  "styles"?: Record<string, unknown> | null;
  "submenuLeaveDelay"?: number;
  "submenuOffset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "submenuOpenDelay"?: number;
  "submenuTrigger"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
}

export interface ImageOptions {
  "alt"?: unknown;
  "circle"?: boolean;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "controls"?: boolean;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "doubleClickZoom"?: boolean;
  "draggable"?: boolean;
  "elements"?: Record<string, unknown> | null;
  "errorContent"?: unknown;
  "fallback"?: unknown;
  "fit"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "height"?: unknown;
  "initialIndex"?: unknown;
  "inputTarget"?: unknown;
  "items"?: unknown[];
  "keyboard"?: boolean;
  "lazy"?: boolean;
  "maskClosable"?: boolean;
  "maskColor"?: unknown;
  "maskOpacity"?: unknown;
  "maxScale"?: number;
  "minScale"?: number;
  "name"?: string;
  "onDownload"?: (...args: any[]) => any | null;
  "onError"?: (...args: any[]) => any | null;
  "onFallback"?: (...args: any[]) => any | null;
  "onLoad"?: (...args: any[]) => any | null;
  "onPreviewChange"?: (...args: any[]) => any | null;
  "onPreviewVisibleChange"?: (...args: any[]) => any | null;
  "onTransform"?: (...args: any[]) => any | null;
  "placeholder"?: string;
  "portalContainer"?: unknown;
  "preview"?: unknown;
  "previewGroup"?: unknown;
  "previewList"?: unknown;
  "previewMask"?: unknown;
  "previewMaskText"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "rotateStep"?: number;
  "rounded"?: boolean;
  "scaleStep"?: number;
  "source"?: unknown;
  "src"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "trajectory"?: unknown;
  "triggerTarget"?: unknown;
  "valueTarget"?: unknown;
  "wheelZoom"?: boolean;
  "width"?: unknown;
  "zIndex"?: number;
}

export interface InputNumberOptions {
  "changeOnBlur"?: boolean;
  "changeOnWheel"?: boolean;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "controls"?: boolean;
  "decimalSeparator"?: unknown;
  "defaultValue"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "focusOutline"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "formatter"?: unknown;
  "inputMode"?: unknown;
  "inputTarget"?: unknown;
  "keyboard"?: boolean;
  "max"?: unknown;
  "min"?: unknown;
  "mode"?: unknown;
  "name"?: string;
  "onBlur"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onFocus"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "onPressEnter"?: (...args: any[]) => any | null;
  "onStep"?: (...args: any[]) => any | null;
  "parser"?: unknown;
  "placeholder"?: string;
  "portalContainer"?: unknown;
  "precision"?: number;
  "prefix"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "step"?: number | string | null;
  "stringMode"?: boolean;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "target"?: unknown;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
}

export interface InputOTPOptions {
  "accept"?: unknown;
  "autoFocus"?: boolean;
  "autocomplete"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "defaultValue"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "focusOutline"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "formatter"?: unknown;
  "inputMode"?: unknown;
  "inputTarget"?: unknown;
  "length"?: number;
  "mask"?: unknown;
  "name"?: string;
  "onBlur"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onComplete"?: (...args: any[]) => any | null;
  "onFocus"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "placeholder"?: string | unknown[] | null;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "separator"?: string | (...args: any[]) => any | null;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "styles"?: Record<string, unknown> | null;
  "target"?: unknown;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
}

export interface JSONOptions {
  "addEventListener"?: unknown;
  "autocomplete"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "collapsed"?: boolean;
  "container"?: unknown;
  "copy"?: unknown;
  "data"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "editable"?: boolean;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "height"?: unknown;
  "indent"?: number;
  "inputTarget"?: unknown;
  "maxDepth"?: unknown;
  "maxHeight"?: unknown;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "showLine"?: boolean;
  "size"?: string;
  "sortKeys"?: unknown;
  "source"?: unknown;
  "spellcheck"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "tabIndex"?: unknown;
  "toolbar"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "virtual"?: unknown;
  "virtualThreshold"?: unknown;
}

export interface LoadingOptions {
  "blocking"?: boolean;
  "boxStyle"?: Record<string, unknown>;
  "className"?: string;
  "delay"?: number;
  "fullscreen"?: boolean;
  "indicator"?: unknown;
  "lockScroll"?: boolean;
  "maskBlur"?: unknown;
  "maskColor"?: string;
  "onClose"?: (...args: any[]) => any;
  "onOpen"?: (...args: any[]) => any;
  "open"?: boolean;
  "progress"?: unknown;
  "showMask"?: boolean;
  "size"?: "xs" | "sm" | "md" | "lg" | "xl";
  "style"?: Record<string, unknown>;
  "target"?: Element;
  "text"?: unknown;
}

export interface MenuOptions {
  "autoUpdate"?: boolean;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "collapsed"?: boolean;
  "collapsedWidth"?: unknown;
  "container"?: unknown;
  "defaultOpenKeys"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "disabledOverflow"?: unknown;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "expandIcon"?: unknown;
  "flipOnOverflow"?: boolean;
  "forceSubMenuRender"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "inlineIndent"?: unknown;
  "inputTarget"?: unknown;
  "itemDisplay"?: unknown;
  "items"?: unknown[];
  "loop"?: boolean;
  "middleware"?: unknown[];
  "mode"?: unknown;
  "multiple"?: boolean;
  "name"?: string;
  "onClick"?: (...args: any[]) => any | null;
  "onDeselect"?: (...args: any[]) => any | null;
  "onNavigate"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onSelectedKeyChange"?: (...args: any[]) => any | null;
  "onSelectedKeysChange"?: (...args: any[]) => any | null;
  "onTitleClick"?: (...args: any[]) => any | null;
  "openKeys"?: unknown;
  "overflowedIndicator"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "querySelector"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "selectable"?: unknown;
  "selectedKey"?: unknown;
  "selectedKeys"?: unknown;
  "selectionAppearance"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "strategy"?: string;
  "style"?: Record<string, unknown> | null;
  "styles"?: Record<string, unknown> | null;
  "submenuLeaveDelay"?: number;
  "submenuMode"?: unknown;
  "submenuOffset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "submenuOpenDelay"?: number;
  "submenuTrigger"?: unknown;
  "theme"?: unknown;
  "tooltip"?: unknown;
  "triggerTarget"?: unknown;
  "valueTarget"?: unknown;
}

export interface MessageOptions {
  "actions"?: unknown[];
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closable"?: boolean;
  "closeOnClick"?: boolean;
  "container"?: unknown;
  "content"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "duration"?: number;
  "easing"?: string;
  "elements"?: Record<string, unknown> | null;
  "enterDuration"?: number;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "icon"?: unknown;
  "inputTarget"?: unknown;
  "key"?: unknown;
  "leaveDuration"?: number;
  "maxCount"?: number;
  "moveDuration"?: number;
  "name"?: string;
  "onBeforeClose"?: (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onUpdate"?: (...args: any[]) => any | null;
  "pauseOnHover"?: boolean;
  "pauseOnHoverScope"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "showProgress"?: boolean;
  "source"?: unknown;
  "stack"?: unknown;
  "stackClassName"?: unknown;
  "stackStyle"?: Record<string, unknown> | null;
  "style"?: Record<string, unknown> | null;
  "styles"?: Record<string, unknown> | null;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
  "zIndex"?: number;
}

export interface ModalOptions {
  "afterClose"?: (...args: any[]) => any | null;
  "afterOpenChange"?: (...args: any[]) => any | null;
  "animation"?: unknown;
  "attrs"?: Record<string, unknown> | null;
  "autoFocus"?: unknown;
  "autoLoading"?: unknown;
  "autoOpen"?: unknown;
  "buttonType"?: unknown;
  "buttons"?: unknown[];
  "cancelText"?: unknown;
  "center"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closable"?: boolean | Record<string, unknown> | null;
  "closeIcon"?: unknown;
  "closeOnClick"?: boolean;
  "closeOnEscape"?: boolean;
  "closeOnMask"?: boolean;
  "closeOptions"?: Record<string, unknown> | null;
  "confirmText"?: unknown;
  "container"?: unknown;
  "content"?: unknown;
  "destroyOnHidden"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "duration"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "enterDuration"?: number;
  "focusTrap"?: boolean;
  "footer"?: unknown;
  "forceRender"?: boolean;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "fullscreen"?: unknown;
  "header"?: unknown;
  "href"?: unknown;
  "id"?: unknown;
  "inputTarget"?: unknown;
  "key"?: unknown;
  "label"?: unknown;
  "leaveDuration"?: number;
  "lockScroll"?: boolean;
  "maskAnimation"?: unknown;
  "maskBlur"?: unknown;
  "maskClassName"?: unknown;
  "maskColor"?: unknown;
  "maskDuration"?: unknown;
  "maskEnterDuration"?: number;
  "maskLeaveDuration"?: number;
  "maskStyle"?: unknown;
  "maxWidth"?: unknown;
  "name"?: string;
  "onBeforeClose"?: (...args: any[]) => any | null;
  "onBeforeOpen"?: (...args: any[]) => any | null;
  "onCancel"?: (...args: any[]) => any | null;
  "onClick"?: (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onConfirm"?: (...args: any[]) => any | null;
  "onDestroy"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "origin"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "rel"?: unknown;
  "required"?: boolean;
  "restoreFocus"?: boolean;
  "role"?: unknown;
  "scrollbarVisibility"?: unknown;
  "showMask"?: boolean;
  "source"?: unknown;
  "style"?: Record<string, unknown> | null;
  "styles"?: Record<string, unknown> | null;
  "target"?: unknown;
  "text"?: unknown;
  "title"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
  "width"?: unknown;
  "zIndex"?: number;
}

export interface NotificationOptions {
  "actions"?: unknown[];
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closable"?: boolean;
  "closeOnClick"?: boolean;
  "container"?: unknown;
  "content"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "duration"?: number;
  "easing"?: string;
  "elements"?: Record<string, unknown> | null;
  "enterDuration"?: number;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "icon"?: unknown;
  "inputTarget"?: unknown;
  "key"?: unknown;
  "leaveDuration"?: number;
  "maxCount"?: number;
  "maxWidth"?: unknown;
  "minWidth"?: unknown;
  "moveDuration"?: number;
  "name"?: string;
  "onAction"?: (...args: any[]) => any | null;
  "onBeforeClose"?: (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onUpdate"?: (...args: any[]) => any | null;
  "pauseOnHover"?: boolean;
  "pauseOnHoverScope"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "showProgress"?: boolean;
  "source"?: unknown;
  "stack"?: unknown;
  "stackClassName"?: unknown;
  "stackStyle"?: Record<string, unknown> | null;
  "style"?: Record<string, unknown> | null;
  "styles"?: Record<string, unknown> | null;
  "title"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
  "width"?: unknown;
  "zIndex"?: number;
}

export interface PaginationOptions {
  "background"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "components"?: unknown;
  "container"?: unknown;
  "count"?: number;
  "current"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "ellipsis"?: unknown;
  "ellipsisJump"?: unknown;
  "first"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "hideOnSinglePage"?: unknown;
  "inputMode"?: unknown;
  "inputTarget"?: unknown;
  "itemRender"?: unknown;
  "jump"?: unknown;
  "last"?: unknown;
  "layout"?: unknown;
  "name"?: string;
  "next"?: unknown;
  "onChange"?: (...args: any[]) => any | null;
  "onNextClick"?: (...args: any[]) => any | null;
  "onPrevClick"?: (...args: any[]) => any | null;
  "onRender"?: (...args: any[]) => any | null;
  "onSizeChange"?: (...args: any[]) => any | null;
  "pageSize"?: unknown;
  "pageSizeOptions"?: unknown[];
  "pagerCount"?: unknown;
  "portalContainer"?: unknown;
  "prev"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "responsive"?: unknown;
  "showJumper"?: unknown;
  "showSizeChanger"?: unknown;
  "showTotal"?: unknown;
  "simple"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "triggerTarget"?: unknown;
  "type"?: string;
  "value"?: unknown;
  "valueTarget"?: unknown;
}

export interface PopconfirmOptions {
  "arrowPadding"?: number;
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "cancelDisabled"?: unknown;
  "cancelText"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnFocusOutside"?: unknown;
  "closeOnOutsidePress"?: boolean;
  "closeOnTabExit"?: boolean;
  "confirmDisabled"?: unknown;
  "confirmText"?: unknown;
  "container"?: unknown;
  "content"?: unknown;
  "danger"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "icon"?: unknown;
  "inputTarget"?: unknown;
  "middleware"?: unknown[];
  "name"?: string;
  "offset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "onCancel"?: (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onConfirm"?: (...args: any[]) => any | null;
  "onConfirmError"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "originalEvent"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "restoreFocus"?: boolean;
  "restoreFocusOnClose"?: unknown;
  "showArrow"?: boolean;
  "showWarning"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "title"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "valueTarget"?: unknown;
}

export interface PopoverOptions {
  "action"?: unknown;
  "arrowPadding"?: number;
  "autoUpdate"?: boolean;
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnFocusOutside"?: unknown;
  "closeOnOutsidePress"?: boolean;
  "closeOnTabExit"?: boolean;
  "container"?: unknown;
  "containsTarget"?: unknown;
  "content"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "focusScope"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "inputTarget"?: unknown;
  "middleware"?: unknown[];
  "name"?: string;
  "offset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "restoreFocus"?: boolean;
  "restoreFocusOnClose"?: unknown;
  "showArrow"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "title"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "valueTarget"?: unknown;
}

export interface ProgressOptions {
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "color"?: unknown;
  "container"?: unknown;
  "direction"?: string;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "format"?: unknown;
  "gapDegree"?: unknown;
  "gapPlacement"?: unknown;
  "inputTarget"?: unknown;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onUpdate"?: (...args: any[]) => any | null;
  "percent"?: unknown;
  "portalContainer"?: unknown;
  "railColor"?: unknown;
  "readOnly"?: boolean;
  "reason"?: unknown;
  "reference"?: unknown;
  "required"?: boolean;
  "showInfo"?: unknown;
  "silent"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "steps"?: unknown;
  "strokeColor"?: unknown;
  "strokeLinecap"?: unknown;
  "strokeWidth"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "success"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
}

export interface RateOptions {
  "character"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "container"?: unknown;
  "count"?: number;
  "defaultValue"?: unknown;
  "direction"?: string;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "half"?: boolean;
  "inputTarget"?: unknown;
  "keyboard"?: boolean;
  "mode"?: unknown;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onHoverChange"?: (...args: any[]) => any | null;
  "originalEvent"?: unknown;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reason"?: unknown;
  "reference"?: unknown;
  "required"?: boolean;
  "serializeValue"?: unknown;
  "silent"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "toggle"?: unknown;
  "tooltips"?: unknown;
  "triggerTarget"?: unknown;
  "user"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
}

export interface ResultOptions {
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "extra"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "icon"?: unknown;
  "inputTarget"?: unknown;
  "name"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "size"?: string | number | null;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "subtitle"?: unknown;
  "title"?: unknown;
  "triggerTarget"?: unknown;
  "valueTarget"?: unknown;
  "viewBox"?: unknown;
  "visible"?: unknown;
}

export interface RippleOptions {
  "color"?: unknown;
  "inside"?: unknown;
  "outside"?: unknown;
}

export interface ScrollOptions {
  "align"?: unknown;
  "axis"?: unknown;
  "behavior"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "content"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "edgeShadow"?: boolean;
  "edgeShadowSize"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "focusable"?: boolean;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "inputTarget"?: unknown;
  "keyboard"?: boolean;
  "name"?: string;
  "offset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "onScroll"?: (...args: any[]) => any | null;
  "onScrollEnd"?: (...args: any[]) => any | null;
  "onScrollStart"?: (...args: any[]) => any | null;
  "onSnapSettle"?: (...args: any[]) => any | null;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reason"?: unknown;
  "reference"?: unknown;
  "required"?: boolean;
  "root"?: unknown;
  "scrollIdleDelay"?: number;
  "scrollbarHideDelay"?: unknown;
  "scrollbarInteractive"?: unknown;
  "scrollbarVisibility"?: unknown;
  "snapAlign"?: unknown;
  "snapAxis"?: unknown;
  "snapBehavior"?: unknown;
  "snapDuration"?: number;
  "snapLoop"?: boolean;
  "snapOnIdle"?: boolean;
  "snapTargets"?: unknown;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "triggerTarget"?: unknown;
  "valueTarget"?: unknown;
  "viewport"?: unknown;
  "wheelAxis"?: unknown;
  "wheelBehavior"?: unknown;
  "wheelPropagation"?: boolean;
  "x"?: unknown;
  "y"?: unknown;
}

export interface SelectOptions {
  "addOnBlur"?: unknown;
  "addOnEnter"?: unknown;
  "addOnTab"?: unknown;
  "autoUpdate"?: boolean;
  "busy"?: boolean;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearContent"?: unknown;
  "clearSearchOnSelect"?: unknown;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "container"?: unknown;
  "creatable"?: unknown;
  "defaultActiveFirstOption"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "emptyText"?: unknown;
  "error"?: boolean;
  "errorText"?: unknown;
  "filterItem"?: unknown;
  "flipOnOverflow"?: boolean;
  "focusOutline"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "getKey"?: (...args: any[]) => any | null;
  "getLabel"?: (...args: any[]) => any | null;
  "getValue"?: (...args: any[]) => any | null;
  "headless"?: unknown;
  "height"?: unknown;
  "hideSelectedOptions"?: unknown;
  "inputTarget"?: unknown;
  "isItemDisabled"?: (...args: any[]) => any | null;
  "itemRender"?: unknown;
  "itemSize"?: number;
  "itemStyles"?: unknown;
  "items"?: unknown[];
  "loading"?: boolean;
  "loadingIcon"?: unknown;
  "loadingText"?: unknown;
  "matchReferenceWidth"?: boolean;
  "maxCount"?: number;
  "maxHeight"?: unknown;
  "maxTagLength"?: number;
  "maxVisibleTags"?: unknown;
  "measureAvailableWidth"?: unknown;
  "measureTagOverflowWidth"?: unknown;
  "measureTagWidth"?: unknown;
  "middleware"?: unknown[];
  "multiple"?: boolean;
  "name"?: string;
  "normalizeTag"?: unknown;
  "onActive"?: (...args: any[]) => any | null;
  "onActiveChange"?: (...args: any[]) => any | null;
  "onBlur"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onDeselect"?: (...args: any[]) => any | null;
  "onFocus"?: (...args: any[]) => any | null;
  "onInputKeyDown"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onPopupScroll"?: (...args: any[]) => any | null;
  "onSearch"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onTagInvalid"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "overscan"?: number;
  "placeholder"?: string;
  "placement"?: string;
  "popupRender"?: unknown;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderControl"?: boolean;
  "renderTag"?: (...args: any[]) => any | null;
  "renderTagOverflow"?: (...args: any[]) => any | null;
  "renderValue"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "searchFields"?: unknown;
  "searchable"?: boolean;
  "selectionAppearance"?: unknown;
  "size"?: string;
  "sortItems"?: unknown;
  "source"?: unknown;
  "status"?: string;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "tagClasses"?: unknown;
  "tagInputMinWidth"?: unknown;
  "tagRemoveContent"?: unknown;
  "tagStyles"?: unknown;
  "tagTextMaxLength"?: unknown;
  "toggleContent"?: unknown;
  "tokenSeparators"?: unknown[] | (...args: any[]) => any | null;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "validateTag"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
  "virtual"?: unknown;
  "virtualThreshold"?: unknown;
}

export interface SliderOptions {
  "allowCross"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "defaultValue"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "dots"?: boolean;
  "elements"?: Record<string, unknown> | null;
  "final"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "handleDisabled"?: unknown;
  "included"?: unknown;
  "inputTarget"?: unknown;
  "keyboard"?: boolean;
  "marks"?: unknown;
  "max"?: unknown;
  "min"?: unknown;
  "name"?: string;
  "onAfterChange"?: (...args: any[]) => any | null;
  "onBeforeChange"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onKeyDown"?: (...args: any[]) => any | null;
  "originalEvent"?: unknown;
  "portalContainer"?: unknown;
  "range"?: unknown;
  "readOnly"?: boolean;
  "reason"?: unknown;
  "reference"?: unknown;
  "required"?: boolean;
  "reverse"?: unknown;
  "serializeValue"?: unknown;
  "silent"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "step"?: number;
  "styles"?: Record<string, unknown> | null;
  "tooltip"?: unknown;
  "triggerTarget"?: unknown;
  "user"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "vertical"?: unknown;
}

export interface SortOptions {
  "animation"?: unknown;
  "beforeMove"?: (...args: any[]) => any | null;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "container"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "draggable"?: boolean;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "handleOnly"?: unknown;
  "inputTarget"?: unknown;
  "items"?: unknown[];
  "keyboard"?: boolean;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onDragCancel"?: (...args: any[]) => any | null;
  "onDragEnd"?: (...args: any[]) => any | null;
  "onDragMove"?: (...args: any[]) => any | null;
  "onDragStart"?: (...args: any[]) => any | null;
  "orientation"?: string;
  "originalEvent"?: unknown;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reason"?: unknown;
  "reference"?: unknown;
  "required"?: boolean;
  "serializeValue"?: unknown;
  "showActions"?: unknown;
  "showHandle"?: unknown;
  "silent"?: unknown;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "triggerTarget"?: unknown;
  "valueTarget"?: unknown;
}

export interface StepsOptions {
  "allowCurrentClick"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clickable"?: unknown;
  "container"?: unknown;
  "current"?: unknown;
  "direction"?: string;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "event"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "initial"?: unknown;
  "inputTarget"?: unknown;
  "itemRender"?: unknown;
  "items"?: unknown[];
  "key"?: unknown;
  "labelPlacement"?: unknown;
  "name"?: string;
  "notifySame"?: unknown;
  "onChange"?: (...args: any[]) => any | null;
  "originalEvent"?: unknown;
  "percent"?: unknown;
  "portalContainer"?: unknown;
  "progressDot"?: unknown;
  "readOnly"?: boolean;
  "reason"?: unknown;
  "reference"?: unknown;
  "required"?: boolean;
  "responsive"?: unknown;
  "silent"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "styles"?: Record<string, unknown> | null;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
}

export interface TableOptions {
  "addEventListener"?: unknown;
  "bordered"?: boolean;
  "borderless"?: unknown;
  "caption"?: unknown;
  "checked"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "columnReorder"?: unknown;
  "columns"?: unknown[];
  "container"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "editEnterBehavior"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "emptyText"?: unknown;
  "errorText"?: unknown;
  "expandedKeys"?: unknown[];
  "filteredTotal"?: unknown;
  "filters"?: unknown[];
  "fixedLayout"?: boolean;
  "footer"?: unknown;
  "footerEnd"?: unknown;
  "footerStart"?: unknown;
  "forceRenderExpanded"?: boolean;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "getKey"?: (...args: any[]) => any | null;
  "height"?: unknown;
  "hover"?: unknown;
  "inputTarget"?: unknown;
  "isItemDisabled"?: (...args: any[]) => any | null;
  "items"?: unknown[];
  "keepStaleData"?: boolean;
  "key"?: unknown;
  "keyboardNavigation"?: unknown;
  "load"?: unknown;
  "loading"?: boolean;
  "loadingText"?: unknown;
  "maxHeight"?: unknown;
  "minWidth"?: unknown;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onColumnReorder"?: (...args: any[]) => any | null;
  "onColumnResize"?: (...args: any[]) => any | null;
  "onColumnResizeEnd"?: (...args: any[]) => any | null;
  "onLoad"?: (...args: any[]) => any | null;
  "onLoadError"?: (...args: any[]) => any | null;
  "onRow"?: (...args: any[]) => any | null;
  "onRowClick"?: (...args: any[]) => any | null;
  "onRowContextMenu"?: (...args: any[]) => any | null;
  "onRowDoubleClick"?: (...args: any[]) => any | null;
  "onRowReorder"?: (...args: any[]) => any | null;
  "onSearchChange"?: (...args: any[]) => any | null;
  "onSelectionChange"?: (...args: any[]) => any | null;
  "overscan"?: number;
  "page"?: unknown;
  "pageSize"?: unknown;
  "pager"?: unknown;
  "portalContainer"?: unknown;
  "preserveSelectedKeys"?: boolean;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "remoteSelectionScope"?: unknown;
  "renderExpanded"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "responsiveMode"?: string;
  "rowClassName"?: unknown;
  "rowExpandable"?: unknown;
  "rowHeight"?: unknown;
  "rowReorder"?: unknown;
  "scrollPolicy"?: unknown;
  "searchMatcher"?: unknown;
  "searchValue"?: unknown;
  "selectedKeys"?: unknown;
  "selectionMode"?: unknown;
  "setSelectionRange"?: unknown;
  "shadow"?: unknown;
  "size"?: string;
  "sortKey"?: unknown;
  "sortOrder"?: unknown;
  "source"?: unknown;
  "stickyHeader"?: boolean;
  "stickySummary"?: boolean;
  "striped"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "summary"?: unknown;
  "tabIndex"?: unknown;
  "title"?: unknown;
  "toolbar"?: unknown;
  "toolbarEnd"?: unknown;
  "toolbarStart"?: unknown;
  "total"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "virtual"?: unknown;
  "virtualThreshold"?: unknown;
}

export interface TabsOptions {
  "activationMode"?: unknown;
  "activeKey"?: unknown;
  "addable"?: boolean;
  "animated"?: unknown;
  "centered"?: boolean;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closable"?: boolean;
  "container"?: unknown;
  "createItem"?: unknown;
  "defaultActiveKey"?: unknown;
  "destroyInactive"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "edgeShadow"?: boolean;
  "editable"?: boolean;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "id"?: unknown;
  "indicator"?: unknown;
  "inputTarget"?: unknown;
  "items"?: unknown[];
  "key"?: unknown;
  "label"?: unknown;
  "name"?: string;
  "onAdd"?: (...args: any[]) => any | null;
  "onBeforeChange"?: (...args: any[]) => any | null;
  "onBeforeEdit"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onEdit"?: (...args: any[]) => any | null;
  "orientation"?: string;
  "overflow"?: unknown;
  "overflowMaxHeight"?: number;
  "overflowPopupRender"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "stretch"?: boolean;
  "styles"?: Record<string, unknown> | null;
  "transition"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "valueTarget"?: unknown;
  "wheelPropagation"?: boolean;
}

export interface TagInputOptions {
  "addOnBlur"?: unknown;
  "addOnEnter"?: unknown;
  "addOnTab"?: unknown;
  "beforeAdd"?: (...args: any[]) => any | null;
  "beforeEdit"?: (...args: any[]) => any | null;
  "beforeRemove"?: (...args: any[]) => any | null;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearVisibility"?: unknown;
  "clearable"?: boolean;
  "container"?: unknown;
  "creatable"?: unknown;
  "defaultValue"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "focusOutline"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "inputTarget"?: unknown;
  "inputValue"?: unknown;
  "js"?: unknown;
  "maxTagLength"?: number;
  "maxTags"?: unknown;
  "name"?: string;
  "normalizeTag"?: unknown;
  "onAdd"?: (...args: any[]) => any | null;
  "onBlur"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onEdit"?: (...args: any[]) => any | null;
  "onFocus"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "onInvalid"?: (...args: any[]) => any | null;
  "onKeydown"?: (...args: any[]) => any | null;
  "onRemove"?: (...args: any[]) => any | null;
  "placeholder"?: string;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "tags"?: unknown;
  "tokenSeparators"?: unknown[] | (...args: any[]) => any | null;
  "tokenizeOnPaste"?: unknown;
  "triggerTarget"?: unknown;
  "unique"?: unknown;
  "validateTag"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
}

export interface TagsOptions {
  "addLabel"?: unknown;
  "addOnBlur"?: unknown;
  "addOnEnter"?: unknown;
  "addOnTab"?: unknown;
  "beforeAdd"?: (...args: any[]) => any | null;
  "beforeEdit"?: (...args: any[]) => any | null;
  "beforeRemove"?: (...args: any[]) => any | null;
  "checkable"?: boolean;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closable"?: boolean;
  "container"?: unknown;
  "controlled"?: unknown;
  "creatable"?: unknown;
  "defaultValue"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "editable"?: boolean;
  "elements"?: Record<string, unknown> | null;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "hosted"?: unknown;
  "inputMinWidth"?: number;
  "inputTarget"?: unknown;
  "inputValue"?: unknown;
  "items"?: unknown[];
  "maxCount"?: number;
  "maxTagLength"?: number;
  "maxVisible"?: number;
  "measureAvailableWidth"?: unknown;
  "measureItemWidth"?: unknown;
  "measureOverflowWidth"?: unknown;
  "multiple"?: boolean;
  "name"?: string;
  "normalizeTag"?: unknown;
  "onAdd"?: (...args: any[]) => any | null;
  "onAddRequest"?: (...args: any[]) => any | null;
  "onBlur"?: (...args: any[]) => any | null;
  "onChange"?: (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onEdit"?: (...args: any[]) => any | null;
  "onFocus"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "onInvalid"?: (...args: any[]) => any | null;
  "onItemsChange"?: (...args: any[]) => any | null;
  "onKeydown"?: (...args: any[]) => any | null;
  "onOverflow"?: (...args: any[]) => any | null;
  "onRemove"?: (...args: any[]) => any | null;
  "onRemoveRequest"?: (...args: any[]) => any | null;
  "onSearch"?: (...args: any[]) => any | null;
  "overflow"?: unknown;
  "overflowMaxHeight"?: number;
  "overflowPlacement"?: unknown;
  "overflowTrigger"?: unknown;
  "placeholder"?: string;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderOverflow"?: (...args: any[]) => any | null;
  "renderTag"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "scrollbarVisibility"?: unknown;
  "showOverflowPopover"?: unknown;
  "size"?: string;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "tabIndex"?: unknown;
  "tagClassName"?: unknown;
  "tagOverflowClassName"?: unknown;
  "tagRemoveClassName"?: unknown;
  "tagRemoveContent"?: unknown;
  "tagTextClassName"?: unknown;
  "tokenSeparators"?: unknown[] | (...args: any[]) => any | null;
  "tokenizeOnPaste"?: unknown;
  "triggerTarget"?: unknown;
  "type"?: string;
  "unique"?: unknown;
  "validateTag"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
}

export interface TimePickerOptions {
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "busy"?: boolean;
  "cancelText"?: unknown;
  "cellRender"?: unknown;
  "changeOnScroll"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnOutsidePress"?: boolean;
  "closeOnSelect"?: boolean;
  "commitInputOnBlur"?: boolean;
  "confirmDisabled"?: unknown;
  "confirmText"?: unknown;
  "container"?: unknown;
  "createDOM"?: unknown;
  "defaultPickerValue"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "disabledHours"?: unknown;
  "disabledMinutes"?: unknown;
  "disabledSeconds"?: unknown;
  "disabledTime"?: unknown;
  "document"?: Document;
  "draftValueTarget"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "focusOutline"?: unknown;
  "footer"?: unknown;
  "footerEnd"?: unknown;
  "footerStart"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "headless"?: unknown;
  "hideDisabledOptions"?: boolean;
  "hourStep"?: number;
  "inputTarget"?: unknown;
  "match"?: unknown;
  "minuteStep"?: number;
  "name"?: string;
  "needConfirm"?: boolean;
  "nowText"?: unknown;
  "onChange"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onDraftChange"?: (...args: any[]) => any | null;
  "onInput"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onPreviewChange"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "order"?: boolean;
  "placeholder"?: string;
  "placement"?: string;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "preserveInvalidOnBlur"?: boolean;
  "previewValue"?: unknown;
  "rangeSeparator"?: string;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderControl"?: boolean;
  "required"?: boolean;
  "secondStep"?: number;
  "selection"?: string;
  "showCancel"?: boolean;
  "showNow"?: boolean;
  "showSecond"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "use12Hours"?: boolean;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
}

export interface TooltipOptions {
  "arrowPadding"?: number;
  "autoUpdate"?: boolean;
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "container"?: unknown;
  "content"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "followCursor"?: boolean;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "fresh"?: unknown;
  "group"?: unknown;
  "inlinePositioning"?: unknown;
  "inlinePositioningOptions"?: Record<string, unknown> | null;
  "inputTarget"?: unknown;
  "interactiveBorder"?: number;
  "interactiveDebounce"?: number;
  "middleware"?: unknown[];
  "name"?: string;
  "offset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "parentLayerId"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "required"?: boolean;
  "showArrow"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "unique"?: unknown;
  "valueTarget"?: unknown;
  "zIndex"?: number;
}

export interface TransferOptions {
  "checked"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "columns"?: unknown[];
  "container"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "filterItem"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "getKey"?: (...args: any[]) => any | null;
  "getLabel"?: (...args: any[]) => any | null;
  "getValue"?: (...args: any[]) => any | null;
  "height"?: unknown;
  "indeterminate"?: unknown;
  "inputTarget"?: unknown;
  "isItemDisabled"?: (...args: any[]) => any | null;
  "itemRender"?: unknown;
  "items"?: unknown[];
  "maxHeight"?: unknown;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onPageChange"?: (...args: any[]) => any | null;
  "onRowClick"?: (...args: any[]) => any | null;
  "onSearch"?: (...args: any[]) => any | null;
  "oneWay"?: boolean;
  "pagination"?: unknown;
  "portalContainer"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderFooter"?: (...args: any[]) => any | null;
  "renderTitle"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "rowClassName"?: unknown;
  "searchable"?: boolean;
  "serializeValue"?: unknown;
  "size"?: string;
  "sortable"?: boolean;
  "source"?: unknown;
  "status"?: string;
  "styles"?: Record<string, unknown> | null;
  "table"?: unknown;
  "titles"?: unknown[];
  "triggerTarget"?: unknown;
  "type"?: string;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "virtual"?: unknown;
  "virtualThreshold"?: unknown;
}

export interface TreeSelectOptions {
  "add"?: unknown;
  "autoUpdate"?: boolean;
  "beforeCheck"?: (...args: any[]) => any | null;
  "beforeExpand"?: (...args: any[]) => any | null;
  "busy"?: boolean;
  "checkStrictly"?: boolean;
  "checkable"?: boolean;
  "checkedStrategy"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "closeOnSelect"?: boolean;
  "container"?: unknown;
  "defaultExpandedKeys"?: unknown[];
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "expandedKeys"?: unknown[];
  "filterItem"?: unknown;
  "flipOnOverflow"?: boolean;
  "focusOutline"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "getItems"?: (...args: any[]) => any | null;
  "getKey"?: (...args: any[]) => any | null;
  "getLabel"?: (...args: any[]) => any | null;
  "getValue"?: (...args: any[]) => any | null;
  "has"?: unknown;
  "headless"?: unknown;
  "height"?: unknown;
  "indent"?: number;
  "inputTarget"?: unknown;
  "isItemDisabled"?: (...args: any[]) => any | null;
  "itemRender"?: unknown;
  "itemStyles"?: unknown;
  "items"?: unknown[];
  "loadChildren"?: unknown;
  "loadedKeys"?: unknown[];
  "matchReferenceWidth"?: boolean;
  "maxCount"?: number;
  "maxHeight"?: unknown;
  "maxVisibleTags"?: unknown;
  "middleware"?: unknown[];
  "multiple"?: boolean;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onCheck"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onExpand"?: (...args: any[]) => any | null;
  "onLoad"?: (...args: any[]) => any | null;
  "onLoadError"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onRemove"?: (...args: any[]) => any | null;
  "onSearch"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "placeholder"?: string;
  "placement"?: string;
  "popupRender"?: unknown;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderControl"?: boolean;
  "renderIcon"?: (...args: any[]) => any | null;
  "renderTag"?: (...args: any[]) => any | null;
  "renderTagOverflow"?: (...args: any[]) => any | null;
  "required"?: boolean;
  "searchable"?: boolean;
  "showLine"?: boolean;
  "size"?: string;
  "source"?: unknown;
  "status"?: string;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "tagClasses"?: unknown;
  "tagStyles"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
  "virtual"?: unknown;
  "virtualThreshold"?: unknown;
}

export interface TriggerOptions {
  "afterClose"?: (...args: any[]) => any | null;
  "afterOpen"?: (...args: any[]) => any | null;
  "allowReferenceUpdate"?: unknown;
  "applyPosition"?: unknown;
  "arrow"?: unknown;
  "arrowElement"?: unknown;
  "arrowPadding"?: number;
  "autoUpdate"?: boolean;
  "autoUpdateOptions"?: Record<string, unknown> | null;
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeInfo"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnFocusOutside"?: unknown;
  "closeOnOutsidePress"?: boolean;
  "closeOnTabExit"?: boolean;
  "compensateScrollbar"?: unknown;
  "componentType"?: unknown;
  "container"?: unknown;
  "containsTarget"?: unknown;
  "destroyOnClose"?: boolean;
  "destroyOnDeactivate"?: unknown;
  "disabled"?: boolean;
  "document"?: Document;
  "elements"?: Record<string, unknown> | null;
  "exclude"?: unknown;
  "flipOnOverflow"?: boolean;
  "floating"?: unknown;
  "focusOnActivate"?: unknown;
  "focusOnOpen"?: unknown;
  "focusScope"?: unknown;
  "forceRender"?: boolean;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "group"?: unknown;
  "initialFocus"?: unknown;
  "inlinePositioning"?: unknown;
  "inlinePositioningOptions"?: Record<string, unknown> | null;
  "inputTarget"?: unknown;
  "interactiveBorder"?: number;
  "interactiveDebounce"?: number;
  "keyboardActivation"?: boolean;
  "layerKind"?: unknown;
  "lockScroll"?: boolean;
  "manageZIndex"?: unknown;
  "matchReferenceWidth"?: boolean;
  "middleware"?: unknown[];
  "name"?: string;
  "offset"?: number | Record<string, unknown> | (...args: any[]) => any | null;
  "onClose"?: (...args: any[]) => any | null;
  "onInteractionEnter"?: (...args: any[]) => any | null;
  "onInteractionLeave"?: (...args: any[]) => any | null;
  "onOpen"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onPositionError"?: (...args: any[]) => any | null;
  "onPositionUpdate"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "parent"?: unknown;
  "parentLayerId"?: unknown;
  "placement"?: string;
  "portalContainer"?: unknown;
  "position"?: unknown;
  "positionReference"?: unknown;
  "readOnly"?: boolean;
  "record"?: unknown;
  "reference"?: unknown;
  "required"?: boolean;
  "restoreFocus"?: boolean;
  "restoreFocusOnClose"?: unknown;
  "restoreFocusOnDismiss"?: unknown;
  "restoreFocusTarget"?: unknown;
  "scrollLockTarget"?: unknown;
  "setVisible"?: unknown;
  "source"?: unknown;
  "strategy"?: string;
  "styles"?: Record<string, unknown> | null;
  "tabExitTarget"?: unknown;
  "transition"?: unknown;
  "transitionElement"?: unknown;
  "trapFocus"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "useTransformPosition"?: unknown;
  "valueTarget"?: unknown;
  "wasOpen"?: unknown;
  "zIndex"?: number;
}

export interface UploadOptions {
  "abortable"?: unknown;
  "accept"?: unknown;
  "actionVisibility"?: unknown;
  "autoUpload"?: boolean;
  "beforeRemove"?: (...args: any[]) => any | null;
  "beforeUpload"?: (...args: any[]) => any | null;
  "capture"?: unknown;
  "className"?: string;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "click"?: unknown;
  "container"?: unknown;
  "defaultValue"?: unknown;
  "directory"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "downloadable"?: boolean;
  "drag"?: boolean;
  "dragSort"?: boolean;
  "dragText"?: unknown;
  "dropHint"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "files"?: unknown[];
  "formField"?: unknown;
  "formTarget"?: unknown;
  "format"?: unknown;
  "hideTrigger"?: boolean;
  "hideTriggerAtMax"?: boolean;
  "inputName"?: unknown;
  "inputTarget"?: unknown;
  "itemRender"?: unknown;
  "listType"?: unknown;
  "maxCount"?: number;
  "maxSize"?: unknown;
  "multiple"?: boolean;
  "name"?: string;
  "onChange"?: (...args: any[]) => any | null;
  "onDownload"?: (...args: any[]) => any | null;
  "onDrop"?: (...args: any[]) => any | null;
  "onError"?: (...args: any[]) => any | null;
  "onPaste"?: (...args: any[]) => any | null;
  "onPreview"?: (...args: any[]) => any | null;
  "onPreviewChange"?: (...args: any[]) => any | null;
  "onPreviewVisibleChange"?: (...args: any[]) => any | null;
  "onProgress"?: (...args: any[]) => any | null;
  "onReject"?: (...args: any[]) => any | null;
  "onRemove"?: (...args: any[]) => any | null;
  "onSort"?: (...args: any[]) => any | null;
  "onSuccess"?: (...args: any[]) => any | null;
  "openFileDialogOnClick"?: boolean;
  "pastable"?: boolean;
  "portalContainer"?: unknown;
  "previewFile"?: unknown;
  "previewTarget"?: unknown;
  "previewable"?: boolean;
  "progressView"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "removable"?: boolean;
  "removeAttribute"?: unknown;
  "renderExtra"?: (...args: any[]) => any | null;
  "renderFileIcon"?: (...args: any[]) => any | null;
  "renderTrigger"?: (...args: any[]) => any | null;
  "request"?: unknown;
  "required"?: boolean;
  "retryable"?: boolean;
  "serializeValue"?: unknown;
  "setAttribute"?: unknown;
  "showLabel"?: unknown;
  "showList"?: boolean;
  "source"?: unknown;
  "styles"?: Record<string, unknown> | null;
  "tabIndex"?: unknown;
  "thickness"?: unknown;
  "thumbUrl"?: unknown;
  "transformFile"?: unknown;
  "triggerTarget"?: unknown;
  "triggerText"?: unknown;
  "type"?: string;
  "uid"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "zIndex"?: number;
}

export interface WheelPickerOptions {
  "afterClose"?: (...args: any[]) => any | null;
  "afterOpen"?: (...args: any[]) => any | null;
  "beforeClose"?: (...args: any[]) => any | null;
  "beforeOpen"?: (...args: any[]) => any | null;
  "busy"?: boolean;
  "cancelText"?: unknown;
  "classNames"?: Record<string, unknown> | null;
  "classes"?: Record<string, unknown> | null;
  "clearable"?: boolean;
  "closeDelay"?: number;
  "closeOnEscape"?: boolean;
  "closeOnOutsidePress"?: boolean;
  "closeOnSelect"?: boolean;
  "columns"?: unknown[];
  "commitMeta"?: unknown;
  "confirmDisabled"?: unknown;
  "confirmText"?: unknown;
  "container"?: unknown;
  "createDOM"?: unknown;
  "defaultValue"?: unknown;
  "destroyOnClose"?: boolean;
  "disabled"?: boolean;
  "document"?: Document;
  "draftValueTarget"?: unknown;
  "elements"?: Record<string, unknown> | null;
  "focusOutline"?: unknown;
  "footer"?: unknown;
  "footerEnd"?: unknown;
  "footerStart"?: unknown;
  "formField"?: unknown;
  "formTarget"?: unknown;
  "formatValue"?: unknown;
  "headless"?: unknown;
  "inputTarget"?: unknown;
  "itemHeight"?: unknown;
  "loop"?: boolean;
  "matchReferenceWidth"?: boolean;
  "name"?: string;
  "needConfirm"?: boolean;
  "onChange"?: (...args: any[]) => any | null;
  "onClear"?: (...args: any[]) => any | null;
  "onDraftChange"?: (...args: any[]) => any | null;
  "onOpenChange"?: (...args: any[]) => any | null;
  "onSelect"?: (...args: any[]) => any | null;
  "onValueChange"?: (...args: any[]) => any | null;
  "open"?: boolean;
  "openDelay"?: number;
  "panelSynced"?: unknown;
  "placeholder"?: string;
  "placement"?: string;
  "portalContainer"?: unknown;
  "prefix"?: unknown;
  "readOnly"?: boolean;
  "reference"?: unknown;
  "renderControl"?: boolean;
  "required"?: boolean;
  "scrollIdleDelay"?: number;
  "scrollbarVisibility"?: unknown;
  "separator"?: string;
  "showCancel"?: boolean;
  "size"?: string;
  "snapBehavior"?: unknown;
  "snapDuration"?: number;
  "source"?: unknown;
  "status"?: string;
  "styles"?: Record<string, unknown> | null;
  "suffix"?: unknown;
  "trigger"?: string;
  "triggerTarget"?: unknown;
  "value"?: unknown;
  "valueTarget"?: unknown;
  "variant"?: string;
  "visibleItemCount"?: number;
  "wheelPropagation"?: boolean;
}

export interface QXComponents {
  Autocomplete: QXComponentApi<AutocompleteOptions>;
  Carousel: QXComponentApi<CarouselOptions>;
  Cascader: QXComponentApi<CascaderOptions>;
  Collapse: QXComponentApi<CollapseOptions>;
  ColorPicker: QXComponentApi<ColorPickerOptions>;
  DatePicker: QXComponentApi<DatePickerOptions>;
  Drawer: QXComponentApi<DrawerOptions>;
  Dropdown: QXComponentApi<DropdownOptions>;
  Image: QXComponentApi<ImageOptions>;
  InputNumber: QXComponentApi<InputNumberOptions>;
  InputOTP: QXComponentApi<InputOTPOptions>;
  JSON: QXComponentApi<JSONOptions>;
  Loading: QXComponentApi<LoadingOptions>;
  Menu: QXComponentApi<MenuOptions>;
  Message: QXComponentApi<MessageOptions>;
  Modal: QXComponentApi<ModalOptions>;
  Notification: QXComponentApi<NotificationOptions>;
  Pagination: QXComponentApi<PaginationOptions>;
  Popconfirm: QXComponentApi<PopconfirmOptions>;
  Popover: QXComponentApi<PopoverOptions>;
  Progress: QXComponentApi<ProgressOptions>;
  Rate: QXComponentApi<RateOptions>;
  Result: QXComponentApi<ResultOptions>;
  Ripple: QXComponentApi<RippleOptions>;
  Scroll: QXComponentApi<ScrollOptions>;
  Select: QXComponentApi<SelectOptions>;
  Slider: QXComponentApi<SliderOptions>;
  Sort: QXComponentApi<SortOptions>;
  Steps: QXComponentApi<StepsOptions>;
  Table: QXComponentApi<TableOptions>;
  Tabs: QXComponentApi<TabsOptions>;
  TagInput: QXComponentApi<TagInputOptions>;
  Tags: QXComponentApi<TagsOptions>;
  TimePicker: QXComponentApi<TimePickerOptions>;
  Tooltip: QXComponentApi<TooltipOptions>;
  Transfer: QXComponentApi<TransferOptions>;
  TreeSelect: QXComponentApi<TreeSelectOptions>;
  Trigger: QXComponentApi<TriggerOptions>;
  Upload: QXComponentApi<UploadOptions>;
  WheelPicker: QXComponentApi<WheelPickerOptions>;
}

export declare const Components: QXComponents;
